/* TP-LINK WDR7300 */

#define BOARD_PID			"WDR7300"
#define BOARD_NAME			"WDR7300"
#define BOARD_DESC			"TP-LINK WDR7300 Wireless Router"
#define BOARD_VENDOR_NAME	"TP-LINK"
#define BOARD_VENDOR_URL		"https://www.tp-link.com.cn/"
#define BOARD_MODEL_URL		"https://www.tp-link.com.cn/"
#define BOARD_BOOT_TIME		30
#define BOARD_FLASH_TIME		120
#undef BOARD_GPIO_BTN_FN1
#define BOARD_GPIO_BTN_RESET	8
#undef BOARD_GPIO_BTN_WPS
#undef  BOARD_GPIO_LED_ALL
#undef  BOARD_GPIO_LED_WIFI
#undef  BOARD_GPIO_LED_SW2G
#undef  BOARD_GPIO_LED_SW5G
#define  BOARD_GPIO_LED_POWER	3
#undef  BOARD_GPIO_LED_LAN
#undef BOARD_GPIO_LED_WAN
#undef BOARD_GPIO_LED_USB
#undef BOARD_GPIO_LED_ROUTER
#undef  BOARD_GPIO_PWR_USB
#define BOARD_HAS_5G_11AC	1
#define BOARD_NUM_ANT_5G_TX	4
#define BOARD_NUM_ANT_5G_RX	4
#define BOARD_NUM_ANT_2G_TX	2
#define BOARD_NUM_ANT_2G_RX	2
#define BOARD_NUM_ETH_LEDS	1
#define BOARD_HAS_EPHY_L1000	1
#define BOARD_HAS_EPHY_W1000	1
#define BOARD_NUM_UPHY_USB3	0
#define BOARD_USB_PORT_SWAP	0

