RT_DRV_DIR  := mt76x2
RT_DRV_PATH := ../$(RT_DRV_DIR)
RT_DRV_NAME := mt76x2_ap

obj-$(CONFIG_MT76X2_AP) += $(RT_DRV_NAME).o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/crypt_md5.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/crypt_sha2.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/crypt_hmac.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/crypt_aes.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/crypt_arc4.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/mlme.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/action.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/ba_action.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/cmm_wep.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/cmm_wpa.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/cmm_tkip.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/cmm_aes.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/cmm_data.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/cmm_data_pci.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/cmm_mac_pci.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/cmm_sync.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/cmm_sanity.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/cmm_info.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/cmm_cfg.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/cmm_profile.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/cmm_asic.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/cmm_cmd.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/cmm_radar.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/rtmp_init.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/rtmp_init_inf.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/rtmp_timer.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/rt_channel.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/rt_os_util.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/spectrum.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/txpower.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/scan.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/ps.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/uapsd.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/eeprom.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/ee_flash.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/ee_efuse.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/ee_prom.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/tx_rx/wdev_tx.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/mgmt/mgmt_entrytb.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/mgmt/mgmt_ht.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/mac/rtmp_mac.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/mac/ral_nmac.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/mcu/mcu.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/mcu/mcu_and.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/phy/rf.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/phy/phy.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/phy/rt_rf.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/phy/mt_rf.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/phy/rlt_phy.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/phy/rtmp_phy.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/rate_ctrl/ra_ctrl.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/rate_ctrl/alg_legacy.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/rate_ctrl/alg_grp.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/ap.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/ap_assoc.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/ap_auth.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/ap_connect.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/ap_mlme.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/ap_sanity.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/ap_sync.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/ap_wpa.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/ap_data.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/ap_autoChSel.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/ap_qload.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/ap_cfg.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/os/linux/ap_ioctl.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/os/linux/rt_proc.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/os/linux/rt_linux.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/os/linux/rt_profile.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/os/linux/rt_main_dev.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/os/linux/rt_rbus_pci_drv.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/os/linux/rt_rbus_pci_util.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/os/linux/rt_pci_rbus.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/os/linux/pci_main_dev.o

### MT7602/MT7612
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/chips/rtmp_chip.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/chips/rt65xx.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/chips/mt76x2.o
ifeq ($(CONFIG_MT76X2_AP_ATE),y)
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ate/chips/mt76x2_ate.o
endif

#ifeq ($(CONFIG_AGS_SUPPORT),y)
#EXTRA_CFLAGS += -DAGS_ADAPT_SUPPORT
#$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/rate_ctrl/alg_ags.o
#endif

ifeq ($(CONFIG_MT76X2_AP_ATE),y)
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ate/common/rt_ate.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ate/common/ate_pci.o
ifeq ($(CONFIG_MT76X2_AP_QA),y)
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ate/common/rt_qa.o
endif
endif

ifeq ($(CONFIG_MT76X2_AP_LED),y)
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/rt_led.o
endif

ifeq ($(CONFIG_MT76X2_AP_80211AC_VHT),y)
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/vht.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/mgmt/mgmt_vht.o
endif

ifeq ($(CONFIG_MT76X2_AP_80211W_PMF),y)
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/pmf.o
endif

ifeq ($(CONFIG_MT76X2_AP_WSC),y)
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/wsc.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/wsc_tlv.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/crypt_dh.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/wsc_ufd.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/crypt_biginteger.o
ifeq ($(CONFIG_MT76X2_AP_WSC_V2),y)
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/wsc_v2.o
endif
ifeq ($(CONFIG_MT76X2_AP_WSC_NFC_SUPPORT),y)
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/nfc.o
endif
endif

ifeq ($(CONFIG_MT76X2_AP_WDS),y)
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/ap_wds.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/ap_wds_inf.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/client_wds.o
endif

ifeq ($(CONFIG_MT76X2_AP_MBSS),y)
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/ap_mbss.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/ap_mbss_inf.o
endif

ifeq ($(CONFIG_MT76X2_AP_APCLI),y)
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/ap_apcli.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/ap_apcli_inf.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/apcli_assoc.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/apcli_auth.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/apcli_ctrl.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/apcli_sync.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/cmm_mat.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/cmm_mat_iparp.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/cmm_mat_pppoe.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/cmm_mat_ipv6.o
ifeq ($(CONFIG_MT76X2_AP_MAC_REPEATER),y)
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/ap_repeater.o
endif
endif

ifeq ($(CONFIG_MT76X2_AP_GREENAP),y)
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/hw_ctrl/greenap.o
endif

ifeq ($(CONFIG_MT76X2_AP_IGMP_SNOOP),y)
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/igmp_snoop.o
endif

ifeq ($(CONFIG_MT76X2_AP_NETIF_BLOCK),y)
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/netif_block.o
endif

ifeq ($(CONFIG_MT76X2_AP_DLS),y)
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/ap_dls.o
endif

ifeq ($(CONFIG_MT76X2_AP_IDS),y)
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/ap/ap_ids.o
endif

ifeq ($(CONFIG_MT76X2_AP_WAPI),y)
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/wapi.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/wapi_sms4.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/wapi_crypt.o
endif

ifeq ($(CONFIG_MT76X2_AP_DFS),y)
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/cmm_dfs.o
endif

ifeq ($(CONFIG_MT76X2_AP_CARRIER),y)
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/cmm_cs.o
endif

ifeq ($(CONFIG_MT76X2_AP_TXBF_SUPPORT),y)
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/cmm_txbf.o
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/cmm_txbf_cal.o
endif

ifeq ($(CONFIG_MT76X2_AP_CSO),y)
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/naf/net_acc.o
endif

ifeq ($(CONFIG_MT76X2_AP_VIDEO_TURBINE),y)
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/cmm_video.o
endif

ifeq ($(CONFIG_MT76X2_AP_DBG),y)
$(RT_DRV_NAME)-objs += $(RT_DRV_PATH)/common/sys_log.o
endif

###################
#  CFLAGS
##################

EXTRA_CFLAGS  = -Wall -Wstrict-prototypes -Wno-trigraphs -Wno-unused -Wno-declaration-after-statement
EXTRA_CFLAGS += -Idrivers/net/wireless/$(RT_DRV_DIR)/include
ifeq ($(CONFIG_MT76X2_AP_ATE),y)
EXTRA_CFLAGS += -Idrivers/net/wireless/$(RT_DRV_DIR)/ate/include
endif
EXTRA_CFLAGS += -DAGGREGATION_SUPPORT -DPIGGYBACK_SUPPORT -DWMM_SUPPORT -DLINUX
EXTRA_CFLAGS += -DCONFIG_AP_SUPPORT -DUAPSD_SUPPORT -DDOT11_N_SUPPORT -DDOT1X_SUPPORT
EXTRA_CFLAGS += -DAP_SCAN_SUPPORT -DSCAN_SUPPORT
EXTRA_CFLAGS += -DRTMP_MAC_PCI -DRTMP_PCI_SUPPORT
EXTRA_CFLAGS += -DSTATS_COUNT_SUPPORT -DENHANCED_STAT_DISPLAY
EXTRA_CFLAGS += -DRESOURCE_PRE_ALLOC

ifeq ($(CONFIG_RT_FIRST_CARD),2860)
EXTRA_CFLAGS += -DRT_SOC_SUPPORT
endif

# do not lock CountryRegion from EEPROM
EXTRA_CFLAGS += -DEEPROM_COUNTRY_UNLOCK

# provide external Flash memory support
EXTRA_CFLAGS += -DRTMP_FLASH_SUPPORT

# provide internal eFuse memory support
#EXTRA_CFLAGS += -DRTMP_EFUSE_SUPPORT -DCAL_FREE_IC_SUPPORT

# provide roaming support
#EXTRA_CFLAGS += -DIAPP_SUPPORT

# provide information on the current STA population and traffic levels in the QBSS
#EXTRA_CFLAGS += -DAP_QLOAD_SUPPORT -DQLOAD_FUNC_BUSY_TIME_STATS

ifneq ($(CONFIG_RA_HW_NAT_WIFI),y)
EXTRA_CFLAGS += -DCONFIG_RA_NAT_NONE
endif

ifeq ($(CONFIG_RA_NETWORK_WORKQUEUE_BH),y)
EXTRA_CFLAGS += -DWORKQUEUE_BH
endif

### MT7602/MT7612
EXTRA_CFLAGS += -DRT65xx -DMT76x2 -DMT7612
#EXTRA_CFLAGS += -DCONFIG_FPGA_MODE
EXTRA_CFLAGS += -DRLT_MAC -DRLT_BBP -DMT_RF -DRTMP_RF_RW_SUPPORT
EXTRA_CFLAGS += -DA_BAND_SUPPORT
EXTRA_CFLAGS += -DRX_DMA_SCATTER -DCONFIG_ANDES_SUPPORT
EXTRA_CFLAGS += -DNEW_RATE_ADAPT_SUPPORT
EXTRA_CFLAGS += -DFIFO_EXT_SUPPORT
EXTRA_CFLAGS += -DVCORECAL_SUPPORT
EXTRA_CFLAGS += -DDYNAMIC_VGA_SUPPORT
EXTRA_CFLAGS += -DMCS_LUT_SUPPORT -DPEER_DELBA_TX_ADAPT
EXTRA_CFLAGS += -DSPECIFIC_TX_POWER_SUPPORT
EXTRA_CFLAGS += -DRTMP_TEMPERATURE_TX_ALC
#EXTRA_CFLAGS += -DSPECIFIC_BCN_BUF_SUPPORT

ifeq ($(CONFIG_MT76X2_AP_READ_MAC_FROM_MTD),y)
EXTRA_CFLAGS += -DREAD_MAC_FROM_EEPROM
endif

ifeq ($(CONFIG_MT76X2_AP_DBG),y)
EXTRA_CFLAGS += -DDBG
#EXTRA_CFLAGS += -DDBG_DIAGNOSE -DDBG_RX_MCS -DDBG_TX_MCS
EXTRA_CFLAGS += -DSYSTEM_LOG_SUPPORT
endif

ifeq ($(CONFIG_MT76X2_AP_ATE),y)
EXTRA_CFLAGS += -DRALINK_ATE -DCONFIG_RT2880_ATE_CMD_NEW
ifeq ($(CONFIG_MT76X2_AP_QA),y)
EXTRA_CFLAGS += -DRALINK_QA
endif
endif

ifeq ($(CONFIG_MT76X2_AP_DLS),y)
EXTRA_CFLAGS += -DQOS_DLS_SUPPORT
endif

ifeq ($(CONFIG_MT76X2_AP_IDS),y)
EXTRA_CFLAGS += -DIDS_SUPPORT
endif

ifeq ($(CONFIG_MT76X2_AP_DFS),y)
EXTRA_CFLAGS += -DDFS_SUPPORT -DDFS_ATP_SUPPORT
endif

ifeq ($(CONFIG_MT76X2_AP_CARRIER),y)
EXTRA_CFLAGS += -DCARRIER_DETECTION_SUPPORT
endif

ifeq ($(CONFIG_MT76X2_AP_ED_MONITOR),y)
EXTRA_CFLAGS += -DED_MONITOR
endif

ifeq ($(CONFIG_MT76X2_AP_WAPI),y)
EXTRA_CFLAGS += -DWAPI_SUPPORT
endif

ifeq ($(CONFIG_MT76X2_AP_GREENAP),y)
EXTRA_CFLAGS += -DGREENAP_SUPPORT
endif

ifeq ($(CONFIG_MT76X2_AP_MCAST_RATE_SPECIFIC),y)
EXTRA_CFLAGS += -DMCAST_RATE_SPECIFIC
endif

ifeq ($(CONFIG_MT76X2_AP_80211N_DRAFT3),y)
EXTRA_CFLAGS += -DDOT11N_DRAFT3
endif

ifeq ($(CONFIG_MT76X2_AP_80211AC_VHT),y)
EXTRA_CFLAGS += -DDOT11_VHT_AC
endif

ifeq ($(CONFIG_MT76X2_AP_TXBF_SUPPORT),y)
EXTRA_CFLAGS += -DMCS_LUT_SUPPORT -DTXBF_SUPPORT -DVHT_TXBF_SUPPORT
endif

ifeq ($(CONFIG_MT76X2_AP_80211W_PMF),y)
EXTRA_CFLAGS += -DDOT11W_PMF_SUPPORT -DSOFT_ENCRYPT
endif

ifeq ($(CONFIG_MT76X2_AP_LED),y)
EXTRA_CFLAGS += -DLED_CONTROL_SUPPORT
ifeq ($(CONFIG_MT76X2_AP_WSC),y)
EXTRA_CFLAGS += -DWSC_LED_SUPPORT
endif
ifeq ($(CONFIG_MT76X2_AP_WSC_NFC_SUPPORT),y)
EXTRA_CFLAGS += -DWSC_NFC_SUPPORT
endif
endif

ifeq ($(CONFIG_MT76X2_AP_WSC),y)
EXTRA_CFLAGS += -DWSC_AP_SUPPORT
ifeq ($(CONFIG_MT76X2_AP_WSC_V2),y)
EXTRA_CFLAGS += -DWSC_V2_SUPPORT
endif
endif

ifeq ($(CONFIG_MT76X2_AP_LLTD),y)
EXTRA_CFLAGS += -DLLTD_SUPPORT
endif

ifeq ($(CONFIG_MT76X2_AP_WDS),y)
EXTRA_CFLAGS += -DWDS_SUPPORT
endif

ifeq ($(CONFIG_MT76X2_AP_MBSS),y)
EXTRA_CFLAGS += -DMBSS_SUPPORT
ifeq ($(CONFIG_MT76X2_AP_MBSS_NEW_MBSSID_MODE),y)
EXTRA_CFLAGS += -DNEW_MBSSID_MODE
EXTRA_CFLAGS += -DENHANCE_NEW_MBSSID_MODE
endif
endif

ifeq ($(CONFIG_MT76X2_AP_APCLI),y)
EXTRA_CFLAGS += -DAPCLI_SUPPORT -DMAT_SUPPORT
#EXTRA_CFLAGS += -DAPCLI_AUTO_CONNECT_SUPPORT
ifeq ($(CONFIG_MT76X2_AP_MAC_REPEATER),y)
EXTRA_CFLAGS += -DMAC_REPEATER_SUPPORT
endif
ifeq ($(CONFIG_MT76X2_AP_APCLI_CERT),y)
EXTRA_CFLAGS += -DAPCLI_CERT_SUPPORT
endif
endif

ifeq ($(CONFIG_MT76X2_AP_IGMP_SNOOP),y)
EXTRA_CFLAGS += -DIGMP_SNOOP_SUPPORT
endif

ifeq ($(CONFIG_MT76X2_AP_NETIF_BLOCK),y)
EXTRA_CFLAGS += -DBLOCK_NET_IF
endif

ifeq ($(CONFIG_MT76X2_AP_VIDEO_TURBINE),y)
EXTRA_CFLAGS += -DVIDEO_TURBINE_SUPPORT
endif

ifeq ($(CONFIG_MT76X2_AP_HDR_TRANS),y)
EXTRA_CFLAGS += -DHDR_TRANS_SUPPORT
endif

ifeq ($(CONFIG_MT76X2_AP_CSO),y)
EXTRA_CFLAGS += -DCONFIG_CSO_SUPPORT -DCONFIG_TSO_SUPPORT
endif

ifeq ($(CONFIG_MT76X2_AP_DELAYED_TCP_ACK),y)
EXTRA_CFLAGS += -DDELAYED_TCP_ACK
endif

ifeq ($(CONFIG_MT76X2_AP_EXT_CHANNEL_LIST),y)
EXTRA_CFLAGS += -DEXT_BUILD_CHANNEL_LIST
endif

ifeq ($(CONFIG_MT76X2_AP_SINGLE_SKU),y)
EXTRA_CFLAGS += -DSINGLE_SKU_V2
endif

ifeq ($(CONFIG_MT76X2_AP_MEMORY_OPTIMIZATION),y)
EXTRA_CFLAGS += -DMEMORY_OPTIMIZATION
endif

ifeq ($(CONFIG_MT76X2_AP_SNMP),y)
EXTRA_CFLAGS += -DSNMP_SUPPORT
endif

ifeq ($(CONFIG_MT76X2_AP_BIG_ENDIAN),y)
EXTRA_CFLAGS += -DRT_BIG_ENDIAN
endif

ifeq ($(CONFIG_MT76X2_AP_MC_SUPPORT),y)
EXTRA_CFLAGS += -DMULTIPLE_CARD_SUPPORT
endif
