# x86
STAGING_DIR     ?=
BIN             ?=
LIBEXEC         ?=
CC              := mipsel-linux-uclibc-gcc
CPP             := mipsel-linux-uclibc-g++
STRIP           := mipsel-linux-uclibc-strip
RM              ?= rm
PLATFORM        := mips
TARGET_DIR      ?= .
MY_CFLAGS       ?=

#$(info "2- $(CC) all:$(ALL_CFLAGS) cpp:$(CPPFLAGS) cdefs:$(CDEFS) copt:$(COPT)")

include rules.mk
