# Makefile for uClibc
#
# Copyright (C) 2000-2005 Erik Andersen <andersen@uclibc.org>
#
# Licensed under the LGPL v2.1, see the file COPYING.LIB in this tarball.
#

CSRC-y := brk.c __syscall_error.c sigaction.c
SSRC-y := __longjmp.S bsd-_setjmp.S bsd-setjmp.S clone.S mmap.S mmap64.S \
	  setjmp.S sync_file_range.S syscall.S syscall6.S vfork.S

SSRC-$(UCLIBC_HAS_ADVANCED_REALTIME) += posix_fadvise64.S
SSRC-$(UCLIBC_HAS_CONTEXT_FUNCS) += makecontext.S setcontext.S getcontext.S swapcontext.S
