# Makefile for uClibc-ng
# Licensed under the LGPL v2.1 or later, see the file COPYING.LIB in this tarball.

ifeq ($(UCLIBC_HAS_FENV),y)
libm_ARCH_SRC:=$(wildcard $(libm_ARCH_DIR)/*.c)
libm_ARCH_OBJ:=$(patsubst $(libm_ARCH_DIR)/%.c,$(libm_ARCH_OUT)/%.o,$(libm_ARCH_SRC))
endif

libm_ARCH_OBJS:=$(libm_ARCH_OBJ)

ifeq ($(DOPIC),y)
libm-a-y+=$(libm_ARCH_OBJS:.o=.os)
else
libm-a-y+=$(libm_ARCH_OBJS)
endif
libm-so-y+=$(libm_ARCH_OBJS:.o=.os)
