/*
** Copyright (c) 2009-2010 by Silicon Laboratories
**
** $Id: si_voice_version.c,v 1.1 2010-07-30 07:55:38 qwert Exp $
**
** si_voice_version.c
** ProSLIC API Version
**
** Author(s): 
** cdp
**
** Distributed by: 
** Silicon Laboratories, Inc
**
** This file contains proprietary information.	 
** No dissemination allowed without prior written permission from
** Silicon Laboratories, Inc.
** 
** THIS FILE IS AUTOGENERATED - DO NOT MODIFY
**
*/

char *SiVoiceAPIVersion = "5.2.1";
