.TH UCLIBC-LDD 1
.SH NAME
uclibc-ldd \- Print shared library dependencies
.SH SYNOPSIS
.B uclibc-ldd
[
.B options
]
.B file...
.SH DESCRIPTION
Prints shared library dependencies.
.SH BUGS
Maybe.

.SH AUTHORS
Erik Andersen <andersen@codepoet.org>
.br
Manual page written by David Schleef <ds@schleef.org>
.SH SEE ALSO
.BR ldd (1)
