CFLAGS-pt-raise.c = -DNOT_IN_libc -DIS_IN_libpthread

ASFLAGS-pthread_spin_lock.S = -DNOT_IN_libc -DIS_IN_libpthread
ASFLAGS-pthread_spin_trylock.S = -DNOT_IN_libc -DIS_IN_libpthread

libc_arch_a_CSRC = libc-tls.c

