#
# Makefile for the rtl8367
#

# api for old ASIC
obj-$(CONFIG_RTL8367_API_8370)		+= api_8370/

# api for new ASIC
obj-$(CONFIG_RTL8367_API_8367B)		+= api_8367b/

# common driver
obj-$(CONFIG_RTL8367)			+= ralink_smi.o
obj-$(CONFIG_RTL8367)			+= rtl8367_drv.o

