# Makefile for uClibc NPTL
#
# Copyright (C) 2009 Bernhard Reutner-Fischer <uclibc@uclibc.org>
#
# Licensed under the LGPL v2.1, see the file COPYING.LIB in this tarball.
#

libpthread_linux_arch_SSRC =
libpthread_linux_arch_CSRC = pthread_once.c

libc_linux_arch_CSRC = fork.c

ASFLAGS += -DUSE___THREAD
