#!/bin/sh
echo "======================= BUILD_CI $1 ======================="

basedir="/opt/rt-n56u"
rm -f $basedir/trunk/images/*.trx
./build_firmware_modify $1 > build.log 2>&1 &

while true ;do
	sleep 10
	echo "===================================================================================================="
	process_status="$(pgrep -f build_firmware_modify)"

	if [ -z "$process_status" ] ;then
		echo "Build script is exited"
		if [ -f $basedir/trunk/images/*.trx ]; then
			tail -20 build.log && exit 0
		elif [ "$rebuild" != "1" ] && tail -10 build.log |grep -q libssl ; then
			echo "openssl parallel make bug, rebuild..."
			tail -30 build.log && rebuild=1
			./build_firmware_modify $1 > build.log 2>&1 &
		else
			tail -60 build.log && exit 1
		fi
	else
		echo "$(tail -2 build.log)"
	fi
done
