#!/bin/sh
[ -z "$1" ] && echo "Please run '$0 PRODUCT_NAME' to start build (see 'configs/templates/') " && exit 1 
if [ ! -f configs/templates/$1.config ] ; then
	echo "configs/templates/$1.config not found "
	exit 1
fi

rm -f nohup.out
touch nohup.out
nohup ./build_firmware_modify $1 &

tail_last=test
while true ;do
echo "===================================================================================================="
tail_latest=$(tail -1 nohup.out)

if [ "$tail_latest" = "make[1]: Leaving directory \`/opt/rt-n56u/trunk/vendors'" ];then
	tail -20 nohup.out
	exit 0
elif [ "$tail_latest" = "$tail_last" ];then
	tail -60 nohup.out
	exit 1
fi
tail_last=$(tail -1 nohup.out)
tail -4 nohup.out
sleep 30
done

