#!/bin/sh
rm -f nohup.out
touch nohup.out
nohup ./build_firmware_k2_nousb &

tail_last=test
while true ;do
echo -e "\n==================================================="
tail_latest=$(tail -1 nohup.out)

if [ "$tail_latest" = "make[1]: Leaving directory \`/opt/rt-n56u/trunk/vendors'" ];then
	tail -20 nohup.out
	exit 0
elif [ "$tail_latest" = "$tail_last" ];then
	tail -60 nohup.out
	exit 1
fi
tail_last=$(tail -1 nohup.out)
tail -4 nohup.out
sleep 30
done
