#!/bin/sh
[ -z "$1" ] && echo "Please run '$0 PRODUCT_NAME' to start build (see 'configs/templates/') " && exit 1 
if [ ! -f configs/templates/$1.config ] ; then
	echo "configs/templates/$1.config not found "
	exit 1
fi

rm -f nohup.out
touch nohup.out
nohup ./build_firmware_modify $1 &

while true ;do
	sleep 10
	echo "===================================================================================================="
	process_status=$(ps aux |grep build_firmware_modify |grep -v "grep")

	if [ -z "$process_status" ] ;then
		echo "Build script is exit"
		if [ "$(tail -1 nohup.out)" = "make[1]: Leaving directory \`/opt/rt-n56u/trunk/vendors'" ]; then
			tail -20 nohup.out && exit 0
		else
			tail -60 nohup.out && exit 1
		fi
	else
		tail -2 nohup.out
	fi
done
