#!/bin/sh

ROOTDIR=`pwd`
export ROOTDIR=$ROOTDIR

if [ ! -f "$ROOTDIR/.config" ] ; then
	echo "Project config file .config not found! Terminate."
	exit 1
fi

echo "-------------CLEAN-ALL---------------"
make clean

rm -rf $ROOTDIR/stage
rm -rf $ROOTDIR/romfs
rm -rf $ROOTDIR/images
rm -rf $ROOTDIR/stage

. $ROOTDIR/.config
if [ -d $ROOTDIR/merge/$CONFIG_FIRMWARE_PRODUCT_ID ]; then
	rm -rf $ROOTDIR/merge/$CONFIG_FIRMWARE_PRODUCT_ID
fi

