#!/bin/sh

ROOTDIR=`pwd`
export ROOTDIR=$ROOTDIR

if [ ! -f "$ROOTDIR/.config" ] ; then
	echo cp -fv "$ROOTDIR/configs/templates/n56u_dlna.config" "$ROOTDIR/.config"
fi

if [ -f "$ROOTDIR/linux-3.4.x/.config" ] ; then
	cp "$ROOTDIR/linux-3.4.x/.config" /tmp/linux-3.4.x-config
fi

if [ -f "$ROOTDIR/user/busybox/busybox-1.24.x/.config" ] ; then
	cp "$ROOTDIR/user/busybox/busybox-1.24.x/.config" /tmp/busybox-1.24.x-config
fi

if [ ! -f "$ROOTDIR/.config" ] ; then
	echo "Project config file .config not found! Terminate."
	exit 1
fi

echo "-------------CLEAN-ALL---------------"
rm -rf $ROOTDIR/stage
make clean

rm -rfv $ROOTDIR/romfs
rm -rfv $ROOTDIR/images
rm -rfv $ROOTDIR/stage
. $ROOTDIR/.config
if [ -d $ROOTDIR/merge/$CONFIG_FIRMWARE_PRODUCT_ID ]; then 
	sudo rm -rf $ROOTDIR/merge/$CONFIG_FIRMWARE_PRODUCT_ID
fi

if [ ! -f "$ROOTDIR/linux-3.4.x/.config" ] ; then
	cp /tmp/linux-3.4.x-config "$ROOTDIR/linux-3.4.x/.config" 
fi

if [ ! -f "$ROOTDIR/user/busybox/busybox-1.24.x/.config" ] ; then
	cp /tmp/busybox-1.24.x-config "$ROOTDIR/user/busybox/busybox-1.24.x/.config" 
fi