.TH LDD 1 2005-08-15 uClibc "Linux Programmer's Manual"
.SH NAME
ldd \- Print shared library dependencies
.SH SYNOPSIS
.B ldd
[
.B OPTIONS
]
.B FILE ...
.SH DESCRIPTION
Prints shared library dependencies.
.SH OPTIONS
None actually, we lied about that part.
.SH BUGS
Probably, make sure you complain when you find them:
.br
http://bugs.uclibc.org/
