#
# Makefile for pass some protocol
#

obj-$(CONFIG_NET_PPPOE_IPV6_PTHROUGH) += pthrough.o
obj-$(CONFIG_NET_PPPOE_IPV6_PTHROUGH) += pppoe_pthrough.o
obj-$(CONFIG_NET_PPPOE_IPV6_PTHROUGH) += ipv6_pthrough.o

