#
# Makefile for the rtl8366
#

EXTRA_CFLAGS += -D_LITTLE_ENDIAN
CFLAGS += -D_LITTLE_ENDIAN

#obj-m += rtl8366SR.o

#rtl8366SR-objs := rmain.o rtl8366s_api.o rtl8366s_asicdrv.o smi.o rtl8366s_greenethernet.o
