# Makefile for uClibc
#
# Copyright (C) 2000-2006 Erik Andersen <andersen@uclibc.org>
#
# Licensed under the LGPL v2.1, see the file COPYING.LIB in this tarball.
#

CSRC := bsdsetjmp.c clone.c \
	sram-alloc.c sram-free.c dma-memcpy.c cacheflush.c

SSRC := __longjmp.S setjmp.S bsd-_setjmp.S

ARCH_HEADERS := bfin_fixed_code.h bfin_l1layout.h bfin_sram.h
