# Makefile for uClibc
#
# Copyright (C) 2000-2006 Erik Andersen <andersen@uclibc.org>
#
# Licensed under the LGPL v2.1, see the file COPYING.LIB in this tarball.
#

libm_ARCH_fpu_DIR := $(libm_SUBARCH_DIR)/fpu
libm_ARCH_fpu_OUT := $(libm_SUBARCH_OUT)/fpu
-include $(libm_ARCH_fpu_DIR)/Makefile.arch

