# Makefile for uClibc
#
# Copyright (C) 2001 SuperH (UK) Ltd.
# Copyright (C) 2003 Paul Mundt <lethal@linux-sh.org>
#
# Licensed under the LGPL v2.1, see the file COPYING.LIB in this tarball.

top_srcdir=../../../../
top_builddir=../../../../
all: objs
include $(top_builddir)Rules.mak
include Makefile.arch
include $(top_srcdir)Makerules
TOPDIR=../../../../
include $(TOPDIR)Rules.mak
