/* ASUS RT-N65U */

#define BOARD_PID		"RT-N65U"
#define BOARD_NAME		"RT-N65U"
#define BOARD_DESC		"ASUS RT-N65U Wireless Router"
#define BOARD_VENDOR_NAME	"ASUSTek Computer Inc."
#define BOARD_VENDOR_URL	"http://www.asus.com/"
#define BOARD_MODEL_URL		"http://www.asus.com/Networking/RTN65U/"
#define BOARD_BOOT_TIME		40
#define BOARD_FLASH_TIME	150
#define BOARD_GPIO_BTN_RESET	13
#define BOARD_GPIO_BTN_WPS	26
#define BOARD_GPIO_LED_ALL	10
#undef  BOARD_GPIO_LED_WIFI
#define BOARD_GPIO_LED_POWER	0
#define BOARD_GPIO_LED_LAN	19
#define BOARD_GPIO_LED_WAN	27
#define BOARD_GPIO_LED_USB	24
#undef  BOARD_GPIO_LED_ROUTER
#undef  BOARD_GPIO_PWR_USB
#define BOARD_HAS_5G_11AC	0
#define BOARD_NUM_ANT_5G_TX	3
#define BOARD_NUM_ANT_5G_RX	3
#define BOARD_NUM_ANT_2G_TX	2
#define BOARD_NUM_ANT_2G_RX	2
#define BOARD_NUM_ETH_LEDS	2
#define BOARD_HAS_EPHY_L1000	1
#define BOARD_HAS_EPHY_W1000	1
#define BOARD_NUM_UPHY_USB3	2
