# Generate a list of devices for a product
#
# This Makefile isn't used when building targets, it is only for
# testing conversion of product Makefiles to use config.dev
#
# Example usage (from toplevel):
# PRODUCTDIR=vendors/CyberGuard/SG300 make -f vendors/config/Makefile.devlist

ROOTDIR=$(PRODUCTDIR)/../../..
CONFIG_CONFIG=$(PRODUCTDIR)/config.device
LINUX_CONFIG=$(PRODUCTDIR)/config.linux-2.4.x
MODULES_CONFIG=$(PRODUCTDIR)/config.modules
ARCH_CONFIG=$(PRODUCTDIR)/config.arch

-include $(LINUX_CONFIG)
-include $(CONFIG_CONFIG)
-include $(ARCH_CONFIG)
-include $(MODULES_CONFIG)

.PHONY: devlist
devlist:
	@echo $(sort $(DEVICES)) | sed 's/ /\n/g' | grep -v '^-'

include $(PRODUCTDIR)/Makefile
