#!/bin/sh
storage_dir="/etc/storage/chinadns"
filename="chnroute.txt"
origin_file="/etc_ro/chnroute.bz2"

[ ! -d $storage_dir ] && mkdir -p $storage_dir

[ -f $origin_file ] && \
[ ! -f $storage_dir/$filename ] && \
tar jxf $origin_file -C $storage_dir && \
touch /tmp/.modify_etc_storage
