#!/bin/sh

cd /etc/storage/

if [ ! -f "cron/crontabs/admin" ] || [ -z "$(cat cron/crontabs/admin |grep "update_chnroute.sh")" ]; then
	echo "0 8 */15 * * /usr/bin/update_chnroute.sh > /dev/null 2>&1" >> cron/crontabs/admin
else
	exit 0
fi

killall crond > /dev/null 2>&1
if [ "$(nvram get crond_log)" = "1" ]; then
	crond
else
	crond -d8
fi

mtd_storage.sh save > /dev/null 2>&1

if [ $? -eq 0 ]; then
	echo "[ DONE! ]"
else
	echo "[ ERROR! ]"
fi
