#!/bin/sh

DIR=`pwd`

. "$DIR/versions.inc"

TARGET="mipsel-linux-uclibc"
TARGET_DIR="$DIR/src/$TARGET-toolchain"

UCLIBCVER="$UCLIBCVER1"
KERNELVER="$KERNELVER1"
if [ "$1" = "--new" ] ; then
    UCLIBCVER="$UCLIBCVER2"
    KERNELVER="$KERNELVER2"
fi

ID_BINUTILS="binutils-$BINUTILSVER"
ID_GCC="gcc-$GCCVER"
ID_UCLIBC="uClibc-$UCLIBCVER"
ID_TOOLCHAIN="toolchain-$KERNELVER"

echo "==================REMOVE-OLD-TOOLCHAIN=================="
rm -rf $ID_TOOLCHAIN
echo "=================REMOVE-OLD-BUILD-TREE=================="
cd "$TARGET_DIR"
rm -rf build-*
rm -rf $ID_BINUTILS
rm -rf $ID_GCC
rm -rf $ID_UCLIBC
rm -rf include
cd "$DIR"
echo "====================All IS DONE!========================"
