#!/bin/sh

DIR=`pwd`

. $DIR/versions.inc

WDIR=$DIR/src
TARGET=mipsel-linux-uclibc
TARGET_DIR=$WDIR/$TARGET-toolchain

echo "=================REMOVE-OLD-BUILD-TREE=================="
cd ${TARGET_DIR}
rm -rf build-*
rm -rf $BINUTILVER
rm -rf $GCCVER
rm -rf $UCLIBCVER
rm -rf include
rm -rf patches
cd ${DIR}

echo "====================All IS DONE!========================"
