# uClibc-ng project
# Licensed under the LGPL v2.1, see the file COPYING and LICENSE.

libc_linux_arch_CSRC = fork.c
libpthread_linux_arch_CSRC = pthread_once.c
libpthread_linux_arch_SSRC =

CFLAGS-OMIT-fork.c = -DNOT_IN_libc -DIS_IN_libpthread

ASFLAGS-syscall.S = -D_LIBC_REENTRANT
ASFLAGS-mmap.S = -D_LIBC_REENTRANT
