#!/bin/sh

exec 2>&1
exec </dev/null

pwd="$PWD"

if="${PWD##*/zcip_}"

echo "* Upping iface $if"
ip link set dev "$if" up || exec sleep 5

echo "* Starting zcip on $if [$$]"
exec \
env - PATH="$PATH" \
softlimit \
setuidgid root \
zcip -fvv \
    "$if" \
    "$pwd/zcip_handler"
