/* vi: set sw=4 ts=4: */
/* Xtensa ELF shared library loader suppport
 *
 * Copyright (C) 2007 Tensilica Inc.
 *
 * Licensed under the LGPL v2.1, see the file COPYING.LIB in this tarball.
 */

static const char * const _dl_reltypes_tab[] =
{
	"R_XTENSA_NONE",
	"R_XTENSA_32",
	"R_XTENSA_RTLD",
	"R_XTENSA_GLOB_DAT",
	"R_XTENSA_JMP_SLOT",
	"R_XTENSA_RELATIVE",
	"R_XTENSA_PLT",
	"R_XTENSA_UNUSED7",
	"R_XTENSA_OP0",
	"R_XTENSA_OP1",
	"R_XTENSA_OP2",
	"R_XTENSA_ASM_EXPAND",
	"R_XTENSA_ASM_SIMPLIFY",
	"R_XTENSA_UNUSED13",
	"R_XTENSA_UNUSED14",
	"R_XTENSA_GNU_VTINHERIT",
	"R_XTENSA_GNU_VTENTRY",
	"R_XTENSA_DIFF8",
	"R_XTENSA_DIFF16",
	"R_XTENSA_DIFF32",
	"R_XTENSA_SLOT0_OP",
	"R_XTENSA_SLOT1_OP",
	"R_XTENSA_SLOT2_OP",
	"R_XTENSA_SLOT3_OP",
	"R_XTENSA_SLOT4_OP",
	"R_XTENSA_SLOT5_OP",
	"R_XTENSA_SLOT6_OP",
	"R_XTENSA_SLOT7_OP",
	"R_XTENSA_SLOT8_OP",
	"R_XTENSA_SLOT9_OP",
	"R_XTENSA_SLOT10_OP",
	"R_XTENSA_SLOT11_OP",
	"R_XTENSA_SLOT12_OP",
	"R_XTENSA_SLOT13_OP",
	"R_XTENSA_SLOT14_OP",
	"R_XTENSA_SLOT0_ALT",
	"R_XTENSA_SLOT1_ALT",
	"R_XTENSA_SLOT2_ALT",
	"R_XTENSA_SLOT3_ALT",
	"R_XTENSA_SLOT4_ALT",
	"R_XTENSA_SLOT5_ALT",
	"R_XTENSA_SLOT6_ALT",
	"R_XTENSA_SLOT7_ALT",
	"R_XTENSA_SLOT8_ALT",
	"R_XTENSA_SLOT9_ALT",
	"R_XTENSA_SLOT10_ALT",
	"R_XTENSA_SLOT11_ALT",
	"R_XTENSA_SLOT12_ALT",
	"R_XTENSA_SLOT13_ALT",
	"R_XTENSA_SLOT14_ALT"
};
