# uClibc args tests
# Licensed under the GNU Library General Public License, see COPYING.LIB

TESTS = arg_test

include ../Test.mak

export WRAPPER_arg_test = \
	env -i \
	ENVVAR=123 \
	SOMETHING=sldajfasdf
export OPTS_arg_test = a b c d e f g h
