#!/bin/sh

cons="  root root 622"
disk="  root root 660"
null="  root root 666"
urandom="  root root  644"

mkdev () {    # usage: mkdev name [bcu] major minor owner group mode
	if [ "$opt_v" ]; then
		if [ "$opt_d" ]; then
			echo "rm -f $1"
		else
			echo "$1 = $2 $3 $4 $5:$6 $7"
		fi
	fi
	su="" ; [ -z "$FAKED_MODE" ] && su="sudo"
	[ ! "$opt_n" ] && $su rm -f $1 && [ ! "$opt_d" ] && $su mknod $1 $2 $3 $4 && $su chown $5:$6 $1 && $su chmod $7 $1
}

cd $1

mkdev	dev/ram     b	1   1	$disk
mkdev	dev/ram0    b	1   0	$disk

mkdev	dev/mem     c	1   1	$disk
mkdev	dev/kmem    c	1   2	$null
mkdev	dev/null    c	1   3	$null
mkdev	dev/random  c	1   8	$urandom
mkdev	dev/urandom c   1   9   $urandom

mkdev	dev/ptmx    c	5   2	$null

mkdev	dev/ttyS0   c	4   64	$cons
mkdev	dev/ttyS1   c	4   65	$cons
mkdev	dev/console c   5   1   $cons

mkdev   dev/mtdblock0 b  31 0 $disk
mkdev   dev/mtdblock1 b  31 1 $disk
mkdev   dev/mtdblock2 b  31 2 $disk
mkdev   dev/mtdblock3 b  31 3 $disk
mkdev   dev/mtdblock4 b  31 4 $disk
mkdev   dev/mtdblock5 b  31 5 $disk
mkdev   dev/mtdblock6 b  31 6 $disk
mkdev   dev/mtd0      c  90 0 $disk
mkdev   dev/mtd0ro    c  90 1 $disk
mkdev   dev/mtd1      c  90 2 $disk
mkdev   dev/mtd1ro    c  90 3 $disk
mkdev   dev/mtd2      c  90 4 $disk
mkdev   dev/mtd2ro    c  90 5 $disk
mkdev   dev/mtd3      c  90 6 $disk
mkdev   dev/mtd3ro    c  90 7 $disk
mkdev   dev/mtd4      c  90 8 $disk
mkdev   dev/mtd4ro    c  90 9 $disk
mkdev   dev/mtd5      c  90 10 $disk
mkdev   dev/mtd5ro    c  90 11 $disk
mkdev   dev/mtd6      c  90 12 $disk
mkdev   dev/mtd6ro    c  90 13 $disk

mkdev	dev/ppp     c	108	0   $cons
mkdev	dev/pts/0   c	136	0   $cons
mkdev	dev/pts/1   c	136	1   $cons
mkdev	dev/pts/2   c	136	2   $cons
mkdev	dev/pts/3   c	136	3   $cons

mkdev	dev/flash0  c	200	0   $cons
mkdev	dev/gpio    c	252	0   $cons
mkdev	dev/rdm0    c	254	0   $cons
