# Makefile for uClibc
#
# Copyright (C) 2001 by Hewlett-Packard Australia
# Copyright (C) 2000-2005 Erik Andersen <andersen@uclibc.org>
#
# Licensed under the LGPL v2.1, see the file COPYING.LIB in this tarball.
#

CSRC-y := pipe.c __init_brk.c brk.c sbrk.c pread_write.c
SSRC-y := setjmp.S __longjmp.S ___fpscr_values.S clone.S vfork.S

CSRC-$(UCLIBC_LINUX_SPECIFIC) += cacheflush.c
