.\" Copyright 1995-2000 David Engel (david@ods.com)
.\" Copyright 1995 Rickard E. Faith (faith@cs.unc.edu)
.\" Most of this was copied from the README file.  Do not restrict distribution.
.\" May be distributed under the GNU General Public License
.TH LDD 1 "14 March 1998"
.SH NAME
ldd \- print shared library dependencies
.SH SYNOPSIS
.B ldd
.RB [ \-vVdr ]
program|library ...
.SH DESCRIPTION
.B ldd
prints the shared libraries required by each program or shared library
specified on the command line.
If a shared library name does not contain a '/',
.B ldd
attempts to locate the library in the standard locations.
To run
.B ldd
on a shared library in the current directory, a "./" must be prepended
to its name.
.SH OPTIONS
.TP
.B \-v
Print the version number of
.BR ldd .
.TP
.B \-V
Print the version number of the dynamic linker,
.BR ld.so .
.TP
.B \-d
Perform relocations and report any missing functions (ELF only).
.TP
.B \-r
Perform relocations for both data objects and functions, and
report any missing objects (ELF only).
.SH BUGS
.B ldd
does not work very well on libc.so.5 itself.
.PP
.B ldd
does not work on a.out shared libraries.
.PP
.B ldd
does not work with some extremely old a.out programs which were 
built before
.B ldd
support was added to the compiler releases.
If you use
.B ldd
on one of these programs, the program will attempt to run with argc = 0 and
the results will be unpredictable.
.SH AUTHOR
David Engel.
.SH SEE ALSO
.BR ldconfig (8),
.BR ld.so (8).
