#!/bin/sh

cd /etc/storage/

if [ ! -f "cron/crontabs/admin" ] || [ -z "$(cat cron/crontabs/admin |grep "ss-watchcat.sh")" ]; then
	echo "*/10 * * * * /usr/bin/ss-watchcat.sh > /dev/null 2>&1" >> cron/crontabs/admin
else
	exit 0
fi

killall crond > /dev/null 2>&1
if [ "$(nvram get crond_log)" = "1" ]; then
	crond
else
	crond -d8
fi
touch /tmp/.modify_etc_storage
