#!/bin/sh 
#
# Copyright (C) 2017 openwrt-ssr
# Copyright (C) 2017 yushi studio <ywb94@qq.com>
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#
NAME=shadowsocksr
server_process_count=$1
redir_tcp_process=$2
redir_udp_process=$3
tunnel_process=$4
v2ray_process=$5
local_process=$6
pdnsd_process=$7
chinadnsng_process=$8
i=0
sock5_port=$(nvram get socks5_proxy_port)
if echo $server|grep -E "^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$">/dev/null; then         
	server=${server}
else
	server=`cat /etc/storage/ssr_ip`
fi
while [ "1" = "1" ]  #死循环
do 
	sleep 30
	#redir tcp
	if [ $redir_tcp_process -gt 0 ] ;then
		icount=`ps -w | grep ssr-retcp |grep -v grep| wc -l`
		if [ $icount = 0 ] ;then
			logger -t "$NAME" "检测到SS进程挂掉，重新启动!"
			/usr/bin/shadowsocks.sh restart 
			exit 0
		fi
	fi
	#redir udp
	if [ $redir_udp_process -gt 0 ] ;then
		icount=`ps -w  | grep ssr-reudp|grep -v grep| wc -l`
		if [ $icount = 0 ] ;then
			logger -t "$NAME" "检测到SS进程挂掉，重新启动!"
			/usr/bin/shadowsocks.sh restart  
			exit 0
		fi
	fi
	#server
	if [ $server_process_count -gt 0 ] ;then
		icount=`ps -w  | grep ssr-server |grep -v grep| wc -l`
		if [ $icount -lt $server_process_count ]  #如果进程挂掉就重启它
		then
			logger -t "$NAME" "ssr server error.restart!"
			killall -q -9 ssr-server 
			for i in `seq $server_process_count`
			do
				/usr/bin/ssr-server -c /tmp/shadowsocksr_$i.json -u -f /tmp/ssr-server$i.pid   
			done  
		fi   
	fi
	#V2RAY
	if [ $v2ray_process -gt 0 ] ;then
		icount=`ps -w  | grep v2ray |grep -v grep| wc -l`
		if [ $icount -lt $v2ray_process ]  #如果进程挂掉就重启它
		then
			logger -t "$NAME" "检测到V2ray进程挂掉，重新启动!"
			killall -q -9 v2ray
			/tmp/v2ray -config /tmp/v2-redir.json >/dev/null 2>&1 &
		fi   
	fi
	#local
	if [ $local_process -gt 0 ] ;then
		icount=`ps -w  | grep ssr-local |grep -v grep| wc -l`
		if [ $icount -lt $local_process ]  #如果进程挂掉就重启它
		then
			logger -t "$NAME" "ssr local error.restart!"
			killall -q -9 ssr-local
			( /usr/bin/ssr-local -c /tmp/shadowsocksr_s.json -u -l $sock5_port -f /tmp/ssr-local.pid &)
		fi   
	fi
	#pdnsd
	if [ $pdnsd_process -gt 0 ] ;then
		icount=`ps -w  | grep pdnsd |grep -v grep| wc -l`
		if [ $icount -lt $pdnsd_process ]  #如果进程挂掉就重启它
		then
			logger -t "$NAME" "pdnsd tunnel error.restart!"
			kill -9 pdnsd
			/usr/sbin/pdnsd -c /tmp/pdnsd.conf -d &
		fi   
	fi      
	#chinadns-ng
	if [ $chinadnsng_process -gt 0 ] ;then
		icount=`ps -w  | grep chinadns-ng |grep -v grep| wc -l`
		if [ $icount -lt $chinadnsng_process ]  #如果进程挂掉就重启它
		then
			logger -t "$NAME" "chinadns-ng tunnel error.restart!"
			kill -9 chinadns-ng
			kill -9 dns2tcp
			dns2tcp -L"127.0.0.1#5353" -R"$(nvram get tunnel_forward)" >/dev/null 2>&1 &
			chinadns-ng -b 0.0.0.0 -l 65353 -c $(nvram get china_dns) -t 127.0.0.1#5353 -4 china -M -m /tmp/cdn.txt >/dev/null 2>&1 &
			sed -i '/no-resolv/d' /etc/storage/dnsmasq/dnsmasq.conf
			sed -i '/server=127.0.0.1/d' /etc/storage/dnsmasq/dnsmasq.conf
			cat >> /etc/storage/dnsmasq/dnsmasq.conf << EOF
no-resolv
server=127.0.0.1#65353
EOF
		fi   
		icount=`ps -w  | grep dns2tcp |grep -v grep| wc -l`
		if [ $icount -lt $chinadnsng_process ]  #如果进程挂掉就重启它
		then
			logger -t "$NAME" "chinadns-ng tunnel error.restart!"
			kill -9 chinadns-ng
			kill -9 dns2tcp
			dns2tcp -L"127.0.0.1#5353" -R"$(nvram get tunnel_forward)" >/dev/null 2>&1 &
			chinadns-ng -b 0.0.0.0 -l 65353 -c $(nvram get china_dns) -t 127.0.0.1#5353 -4 china -M -m /tmp/cdn.txt >/dev/null 2>&1 &
			sed -i '/no-resolv/d' /etc/storage/dnsmasq/dnsmasq.conf
			sed -i '/server=127.0.0.1/d' /etc/storage/dnsmasq/dnsmasq.conf
			cat >> /etc/storage/dnsmasq/dnsmasq.conf << EOF
no-resolv
server=127.0.0.1#65353
EOF
		fi   
	fi
done
