/* JCG-AC860M */

#define BOARD_PID		"JCG-AC860M"
#define BOARD_NAME		"JCG-AC860M"
#define BOARD_DESC		"JCG AC860M Wireless Router"
#define BOARD_VENDOR_NAME	"JCG"
#define BOARD_VENDOR_URL	"http://www.jcgcn.com/"
#define BOARD_MODEL_URL		"http://www.jcgcn.com/"
#define BOARD_BOOT_TIME		30
#define BOARD_FLASH_TIME	120
#undef BOARD_GPIO_BTN_FN1
#define BOARD_GPIO_BTN_RESET 18
#undef BOARD_GPIO_BTN_WPS
#undef  BOARD_GPIO_LED_ALL
#undef  BOARD_GPIO_LED_WIFI
#undef  BOARD_GPIO_LED_SW2G
#undef  BOARD_GPIO_LED_SW5G
#undef  BOARD_GPIO_LED_POWER
#undef  BOARD_GPIO_LED_LAN
#undef BOARD_GPIO_LED_WAN
#define BOARD_GPIO_LED_USB	15
#undef BOARD_GPIO_LED_ROUTER
#undef  BOARD_GPIO_PWR_USB
#define BOARD_HAS_5G_11AC	1
#define BOARD_NUM_ANT_5G_TX	3
#define BOARD_NUM_ANT_5G_RX	3
#define BOARD_NUM_ANT_2G_TX	3
#define BOARD_NUM_ANT_2G_RX	3
#define BOARD_NUM_ETH_LEDS	1
#define BOARD_HAS_EPHY_L1000	1
#define BOARD_HAS_EPHY_W1000	1
#define BOARD_NUM_UPHY_USB3	1
#define BOARD_USB_PORT_SWAP	0
