# uClibc unistd tests
# Licensed under the GNU Library General Public License, see COPYING.LIB

TESTS = clone errno fork getcwd getopt getopt_long preadwrite vfork

include ../Test.mak

export OPTS_getopt = -abcXXX -9
export OPTS_getopt_long = --add XXX --delete YYY --verbose
