/* HC5761A */

#define BOARD_PID		"HC5761A"
#define BOARD_NAME		"HC5761A"
#define BOARD_DESC		"HiWiFi HC5761A Wireless Router"
#define BOARD_VENDOR_NAME	"HiWiFi"
#define BOARD_VENDOR_URL	"http://www.hiwifi.com/"
#define BOARD_MODEL_URL		"http://www.hiwifi.com/"
#define BOARD_BOOT_TIME		25
#define BOARD_FLASH_TIME	120
#define BOARD_GPIO_BTN_RESET	38
#define BOARD_GPIO_LED_INVERTED
#undef  BOARD_GPIO_BTN_WPS
#undef  BOARD_GPIO_LED_ALL
#define BOARD_GPIO_LED_SW2G	44
#define BOARD_GPIO_LED_SW5G	40
#define BOARD_GPIO_LED_POWER	37
#undef  BOARD_GPIO_LED_LAN
#define BOARD_GPIO_LED_WAN	1
#undef  BOARD_GPIO_LED_USB
#undef  BOARD_GPIO_LED_ROUTER
#define BOARD_HAS_5G_11AC	1
#define BOARD_NUM_ANT_5G_TX	1
#define BOARD_NUM_ANT_5G_RX	1
#define BOARD_NUM_ANT_2G_TX	2
#define BOARD_NUM_ANT_2G_RX	2
#define BOARD_NUM_ETH_LEDS	1
#define BOARD_NUM_ETH_EPHY	3
#define BOARD_GPIO_PWR_USB	41
#define BOARD_GPIO_PWR_USB_ON	0
#define BOARD_HAS_EPHY_L1000	0
#define BOARD_HAS_EPHY_W1000	0
