.\" Jean II - HPL - 2004-2007
.\" iftab.5
.\"
.\" Traduction 2004/08/25 Maxime CHARPENNE (voir
.\" http://www.delafond.org/traducmanfr/)
.\" 1ère traduction        : version 27-pre25
.\" Mise à jour 2007/09    : version 29-pre21
.\" Mise à jour 2007/10    : version 30-pre1
.\" Mise à jour 2007/10/29 : version 30-pre3
.\"
.TH IFTAB 5 "26 février 2007" "wireless-tools" "Manuel du Programmeur Linux"
.\"
.\" NAME part
.\"
.SH NOM
iftab \- informations statiques sur les interfaces réseau
.\"
.\" DESCRIPTION part
.\"
.SH DESCRIPTION
Le fichier
.B /etc/iftab
contient de l'information descriptive à propos des diverses interfaces réseau.
.B iftab
n'est utilisé que par le programme
.IR ifrename (8)
pour assigner un nom d'interface réseau cohérent à chaque interface réseau.
.PP
.B /etc/iftab
définit un ensemble de
.IR correspondances " («\ " mappings "\ »)."
Chaque correspondance contient un nom d'interface et un ensemble de sélecteurs
(«\ selectors\ »). Les sélecteurs permettent à
.B ifrename
d'identifier chaque interface réseau du système. Si une interface réseau
correspond à tous les descripteurs d'une correspondance,
.B ifrename
essaye de changer le nom de l'interface par le nom de l'interface donné dans la
correspondance.
.\"
.\" MAPPINGS part
.\"
.SH CORRESPONDANCES («\ MAPPINGS\ »)
Chaque correspondance est décrite sur une ligne distincte, elle commence avec
.IR "interface name" " (nom d'interface),"
et contient un ensemble de
.RI "descripteurs («\ " descriptors "\ »),"
séparés par des espaces ou des tabulations.
.PP
La relation entre les descripteurs d'une correspondance est un
.IR "et logique" .
Une correspondance s'applique à une interface réseau seulement si tous les
descripteurs s'appliquent. Si une interface réseau ne supporte pas un
descripteur particulier, elle ne s'appliquera à aucune correspondance qui
utilise ce descripteur.
.PP
Si vous voulez utiliser des descripteurs alternatifs pour un nom d'interface
(ou logique), spécifiez deux correspondances différentes avec le même nom
d'interface (une par ligne).
.B Ifrename
utilise toujours la première correspondance en commençant par la
.I fin
de
.BR iftab ,
donc les correspondances les plus restrictives devraient être définies en
dernier.
.\"
.\" INTERFACE NAME part
.\"
.SH NOM D'INTERFACE
La première partie de chaque correspondance est un nom d'interface. Si une
interface réseau correspond à tous les descripteurs d'une correspondance,
.B ifrename
essaye de changer le nom de l'interface par le nom de l'interface donné dans la
correspondance.
.PP
Le nom de l'interface d'une correspondance est soit un nom d'interface complet
(comme
.IR eth2 " ou " wlan1 )
soit un motif de nom d'interface contenant un seul caractère joker (comme
.IR eth* " ou " wlan* ).
Dans le cas d'un caractère joker («\ wildcard\ »), le noyau remplace le
caractère '*' par le plus petit entier disponible faisant un nom d'interface
unique. Le caractère joker est supporté seulement pour les noyaux 2.6.1 et
2.4.30 et plus.
.PP
Il est déconseillé d'essayer de faire correspondre des interfaces à des noms
d'interface par défaut tels que
.IR eth0 ", " wlan0 " or " ppp0 .
Le noyau les utilise comme nom par défaut pour toute nouvelle interface,
il est donc très probable qu'une interface portant ce nom existe déjà et
empêche ifrename de les utiliser. Même si vous utilisez ces noms, l'interface
peut déjà être active dans certains cas. Ne pas utiliser ces noms permettra de
détecter sur le champ les interfaces non configurées ou les nouvelles
interfaces.
.br
Les bons noms sont uniques et significatifs, comme
.IR mondsl " or " hubprive ,
ou utilisez de plus grand nombre entier, comme
.IR eth5 " or " wlan5 .
Le second type est habituellement plus facile à intégrer dans divers
utilitaires réseau.
.\"
.\" DESCRIPTORS part
.\"
.SH DESCRIPTEURS («\ DESCRIPTORS\ »)
Chaque descripteur est composé d'un nom de descripteur et d'une valeur de
descripteur. Les descripteurs spécifie un attribut statique d'une interface
réseau, le but étant d'identifier de manière unique chaque matériel.
.PP
La plupart des utilisateurs n'utiliseront que le sélecteur
.BR mac ,
malgré ses problèmes potentiels, d'autres sélecteurs conviennent à des
paramétrages plus spécialisés. La plupart des sélecteurs acceptent '*' dans la
valeur du sélecteur pour correspondance joker, et la plupart des sélecteurs
sont indifférents à la casse des caractères.
.TP
.BI mac " adresse mac"
Correspond à l'Adresse MAC de l'interface avec l'adresse MAC spécifiée.
L'adresse MAC de l'interface peut être montrée en utilisant
.IR ifconfig (8)
ou
.IR ip (8).
.br
C'est le plus commun des sélecteurs, vu que chaque interface possède une
adresse MAC unique, ce qui permet de les identifier sans ambigüité.
Malgré tout, certaines interfaces n'ont pas d'adresse MAC valide tant qu'elles
ne sont pas activées\ ; dans certains cas, utiliser ce sélecteur est pertinent
ou impossible.
.TP
.BI arp " type arp"
Fait correspondre le Type ARP («\ ARP Type\ ») (aussi appelé «\ Link Type\ »)
de l'interface avec le type ARP spécifié par un nombre. Le Type ARP de
l'interface peut être montré en utilisant
.IR ifconfig (8)
ou
.IR ip (8),
le type
.B link/ether
correspond à
.B 1
et le type
.B link/ieee802.11
correspond à
.BR 801 .
.br
Ce sélecteur est utile quand un pilote crée plusieurs interfaces réseau pour
une seule carte réseau.
.TP
.BI driver " nom de pilote"
Fait correspondre le Nom de Pilote («\ Driver Name\ ») de l'interface avec le
nom de pilote spécifié. Le Nom de Pilote de l'interface peut être montré en
utilisant
.IR "ethtool -i" (8).
.TP
.BI businfo " information de bus"
Fait correspondre l'Information de Bus («\ Bus Information\ ») de l'interface
avec l'information de bus spécifiée. L'Information de Bus de l'interface peut
être montrée en utilisant
.IR "ethtool -i" (8).
.TP
.BI firmware " version firmware "
Fait correspondre la Version Firmware («\ Firmware Revision\ ») de l'interface
avec l'information de la version firmware. La Version Firmware de l'interface
peut être montrée en utilisant
.IR "ethtool -i" (8).
.TP
.BI baseaddress " addresse de base"
Fait correspondre l'Adresse de Base («\ Base Address\ ») de l'interface avec
l'adresse de base spécifiée. L'Adresse de Base de l'interface peut être montrée
en utilisant
.IR ifconfig (8).
.br
Ce sélecteur n'est utile que pour les cartes ISA et EISA car la plupart des
cartes utilisent l'allocation dynamique pour l'Adresse de Base.
.TP
.BI irq " ligne irq"
Fait correspondre la Ligne IRQ (interruption) de l'interface avec la ligne IRQ
spécifiée. La Ligne IRQ de l'interface peut être montrée en utilisant
.IR ifconfig (8).
.br
Ce sélecteur n'est habituellement pas suffisant pour identifier de manière
unique une interface, car les Lignes IRQ peuvent être partagées.
.TP
.BI iwproto " protocole wireless"
Fait correspondre le Protocole Wireless de l'interface avec le protocole
wireless spécifié. Le Protocole Wireless de l'interface peut être montré
en utilisant
.IR iwconfig (8),
ou
.IR iwgetid (8).
.br
Ce sélecteur n'est valable que pour les interfaces wireless et n'est pas
suffisant pour en identifier une de manière unique.
.TP
.BI pcmciaslot " prise pcmcia "
Fait correspondre le numéro de Prise Pcmpcia («\ Pcmcia Socket \ ») de
l'interface. Le numéro de Prise Pcmpcia de l'interface peut être montré en
utilisant
.IR "cardctl ident" (8).
.br
Ce sélecteur est habituellement supporté pour les cartes 16 bits seulement,
pour les cartes 32 bits il est conseillé d'utiliser le sélecteur
.BR businfo .
.TP
.BI prevname " nom interface précédent"
Fait correspondre le nom de l'interface avant qu'elle soit renommée avec
le nom précédent spécifié.
.br
Ce sélecteur devrait être évité car le nom précédent de l'interface peut varier
en fonction de diverses conditions. Une mise à jour système/noyau/pilote peut
changer le nom original. Dès lors, ifrename ou un autre utilitaire peut la
renommer avant l'exécution de ce sélecteur.
.TP
.BI SYSFS{ nomfichier } " valeur"
Fait correspondre le contenu de l'attribut sysfs donné par nomfichier avec la
valeur spécifiée. Pour les liens symboliques et les répertoires parents, fait
correspondre le nom réel du répertoire de l'attribut sysfs donné par nomfichier
avec la valeur spécifiée.
.br
Une liste des attributs sysfs les plus utiles est donnée dans la section
suivante.
.\"
.\" SYSFS DESCRIPTORS part
.\"
.SH DESCRIPTEURS SYSFS
Sur la plupart des systèmes, les attributs sysfs pour une carte donnée sont
situés dans le répertoire nommé après cette interface dans
.IR /sys/class/net/ .
La plupart des attributs sysfs sont des fichiers, et leurs valeurs peuvent
être lues en utilisant
.IR cat "(1) ou " more (1).
Il est aussi possible de faire des correspondances dans les attributs des
sous-répertoires.
.PP
Certains attributs sysfs sont des liens symboliques qui pointent vers d'autres
répertoires sysfs. Si l'attribut nomfichier est un lien symbolique, l'attribut
sysfs sera résolu avec le nom du répertoire pointé par le lien en utilisant
.IR readlink (1).
La localisation du répertoire dans l'arborescence sysfs est importante aussi.
Si l'attribut nomfichier fini par
.IR /.. ,
l'attribut sysfs sera résolu avec le nom réel du répertoire parent en utilisant
.IR pwd (1).
.PP
Le système de fichier sysfs est supporté seulement avec les noyaux 2.6.X et a
besoin d'être monté (habituellement dans
.IR /sys ).
Les sélecteurs sysfs ne sont pas aussi efficaces que les autres sélecteurs, et
ne devraient donc pas être employés pour le maximum de performance.
.PP
Ci-après les attributs sysfs communs et leurs descripteurs ifrename équivalents.
.TP
.BI SYSFS{address} " valeur"
Comme le descripteur
.BR mac .
.TP
.BI SYSFS{type} " valeur"
Comme le descripteur
.BR arp .
.TP
.BI SYSFS{device} " valeur"
Valable seulement jusqu'au noyau 2.6.20. Comme le sélecteur
.BR businfo .
.TP
.BI SYSFS{..} " valeur"
Valable seulement depuis le noyau 2.6.21. Comme le sélecteur
.BR businfo .
.TP
.BI SYSFS{device/driver} " valeur"
Valable seulement jusqu'au noyau 2.6.20. Comme le sélecteur
.BR driver .
.TP
.BI SYSFS{../driver} " valeur"
Valable seulement depuis le noyau 2.6.21. Comme le sélecteur
.BR driver .
.TP
.BI SYSFS{device/irq} " valeur"
Valable seulement jusqu'au noyau 2.6.20. Comme le sélecteur
.BR irq .
.TP
.BI SYSFS{../irq} " valeur"
Valable seulement depuis le noyau 2.6.21. Comme le sélecteur
.BR irq .
.\"
.\" EXAMPLES part
.\"
.SH EXEMPLES
# Ceci est un commentaire
.br
eth2		mac 08:00:09:DE:82:0E
.br
eth3		driver wavelan interrupt 15 baseaddress 0x390
.br
eth4		driver pcnet32 businfo 0000:02:05.0
.br
air*		mac 00:07:0E:* arp 1
.br                                                                    
myvpn   SYSFS{address} 00:10:83:* SYSFS{type} 1                        
.br                                                                    
bcm*            SYSFS{device} 0000:03:00.0 SYSFS{device/driver} bcm43xx
.br                                                                    
bcm*            SYSFS{..} 0000:03:00.0 SYSFS{../driver} bcm43xx        
.\"
.\" AUTHOR part
.\"
.SH AUTEUR
Jean Tourrilhes \- jt@hpl.hp.com
.\"
.\" TRADUCTION part
.\"
.SH TRADUCTION
Maxime CHARPENNE, octobre 2007 (wireless_tools.30-pre3).
.\"
.\" AVERTISSEMENT part
.\"
.SH AVERTISSEMENT SUR LA TRADUCTION
Il est possible que cette traduction soit imparfaite ou périmée. En cas de
doute, veuillez vous reporter au document original en langue anglaise fourni
avec le programme.
.\"
.\" FILES part
.\"
.SH FICHIERS
.I /etc/iftab
.\"
.\" SEE ALSO part
.\"
.SH VOIR AUSSI
.BR ifrename (8),
.BR ifconfig (8),
.BR ip (8),
.BR ethtool (8),
.BR iwconfig (8).
