#!/bin/sh
script_iptables="/etc/storage/post_iptables_script.sh"

if [ -z "$(nvram get wan0_ifname6)" ]; then
	logger -st "napt66" "invaild config of WAN ipv6" && exit 1
fi

if [ -z "$(cat $script_iptables |grep -x "disable_ip6tables")" ]; then
	echo "disable_ip6tables" >> $script_iptables
	mtd_storage.sh save > /dev/null 2>&1
	restart_firewall
fi

modprobe napt66 wan_if="$(nvram get wan0_ifname6)" || logger -st "napt66" "load fail!"
