# Makefile for uClibc
#
# Copyright (C) 2000-2005 Erik Andersen <andersen@uclibc.org>
#
# Licensed under the LGPL v2.1 or later, see the file COPYING.LIB in this tarball.
#

CSRC-y := syscall.c sigaction.c __syscall_error.c cacheflush.c

SSRC-y := __longjmp.S setjmp.S bsd-setjmp.S bsd-_setjmp.S vfork.S clone.S \
	sigrestorer.S
