# Makefile for uClibc
#
# Copyright (C) 2000-2005 Erik Andersen <andersen@uclibc.org>
#
# Licensed under the LGPL v2.1, see the file COPYING.LIB in this tarball.
#

CSRC := __init_brk.c brk.c sbrk.c

SSRC := setjmp.S __longjmp.S clone.S sysdep.S syscall.S vfork.S
ifeq ($(UNIFIED_SYSCALL),y)
SSRC += __uClibc_syscall.S
endif
