# Makefile for uClibc
#
# Copyright (C) 2015 Yoshinori Sato
#
# Licensed under the LGPL v2.1 or later, see the file COPYING.LIB in this tarball.
#

CSRC-y := brk.c ptrace.c

SSRC-y := __longjmp.S bsd-_setjmp.S bsd-setjmp.S clone.S setjmp.S vfork.S
