# Makefile for uClibc
#
# Copyright (C) 2015 Yoshinori Sato
#
# Licensed under the LGPL v2.1 or later, see the file COPYING.LIB in this tarball.
#

top_srcdir=../../../../
top_builddir=../../../../
all: objs
include $(top_builddir)Rules.mak
include Makefile.arch
include $(top_srcdir)Makerules
