/* MEIZU MINI R13 */

#define BOARD_PID		"MZ-R13"
#define BOARD_NAME		"MZ-R13"
#define BOARD_DESC		"MEIZU MINI R13 Wireless Router"
#define BOARD_VENDOR_NAME	"Meizu Technology"
#define BOARD_VENDOR_URL	"https://www.meizu.com/"
#define BOARD_MODEL_URL		"https://www.meizu.com/"
#define BOARD_BOOT_TIME		20
#define BOARD_FLASH_TIME	120
#undef BOARD_GPIO_BTN_RESET
#define BOARD_GPIO_BTN_WPS	38
#undef  BOARD_GPIO_BTN_ROUTER
#undef  BOARD_GPIO_LED_ALL
#undef  BOARD_GPIO_LED_WIFI
#undef BOARD_GPIO_LED_SW2G
#undef BOARD_GPIO_LED_POWER
#undef  BOARD_GPIO_LED_LAN
#define BOARD_GPIO_LED_WAN	5
#undef  BOARD_GPIO_LED_USB
#undef  BOARD_GPIO_LED_ROUTER
#undef  BOARD_GPIO_PWR_USB
#define BOARD_HAS_5G_11AC	0
#define BOARD_NUM_ANT_5G_TX	0
#define BOARD_NUM_ANT_5G_RX	0
#define BOARD_NUM_ANT_2G_TX	2
#define BOARD_NUM_ANT_2G_RX	2
#define BOARD_NUM_ETH_LEDS	0
#define BOARD_NUM_ETH_EPHY	1
#define BOARD_HAS_EPHY_L1000	0
#define BOARD_HAS_EPHY_W1000	0
