/* JCG-Q20 */

#define BOARD_PID		"JCG-Q20"
#define BOARD_NAME		"JCG-Q20"
#define BOARD_DESC		"JCG-Q20 Wireless Router"
#define BOARD_VENDOR_NAME	"JCG"
#define BOARD_VENDOR_URL	"http://www.jcgcn.com/"
#define BOARD_MODEL_URL		"http://www.jcgcn.com/"
#define BOARD_BOOT_TIME		20
#define BOARD_FLASH_TIME	120
#define BOARD_GPIO_BTN_RESET	18
#define BOARD_GPIO_BTN_WPS	16
#undef  BOARD_GPIO_LED_ALL
#undef  BOARD_GPIO_LED_WIFI
#define BOARD_GPIO_LED_POWER	15	/* sys_blue: 15, sys_red: 14 */
#undef  BOARD_GPIO_LED_LAN
#undef  BOARD_GPIO_LED_WAN
#undef  BOARD_GPIO_LED_USB
#undef  BOARD_GPIO_LED_ROUTER
#undef  BOARD_GPIO_PWR_USB_ON
#undef  BOARD_GPIO_PWR_USB
#define BOARD_HAS_5G_11AC	1
#define BOARD_HAS_5G_11AX	1
#define BOARD_HAS_2G_11AX	1
#define BOARD_NUM_ANT_5G_TX	2
#define BOARD_NUM_ANT_5G_RX	2
#define BOARD_NUM_ANT_2G_TX	2
#define BOARD_NUM_ANT_2G_RX	2
#define BOARD_NUM_ETH_LEDS	0
#define BOARD_NUM_ETH_EPHY	3
#define BOARD_HAS_EPHY_L1000	1
#define BOARD_HAS_EPHY_W1000	1
