# Makefile for uClibc NPTL
#
# Copyright (C) 2006 Steven J. Hill <sjhill@uclibc.org>
#
# Licensed under the LGPL v2.1, see the file COPYING.LIB in this tarball.
#

libpthread_linux_arch_CSRC = pthread_once.c lowlevellock.c \
	pthread_barrier_init.c pthread_barrier_wait.c pthread_barrier_destroy.c

libc_linux_arch_CSRC = fork.c libc-lowlevellock.c

ASFLAGS += -DUSE___THREAD
