#
# Makefile for the kernel character device drivers.
#

obj-$(CONFIG_RALINK_GPIO)	+= ralink_gpio.o
obj-$(CONFIG_RALINK_GDMA)	+= ralink_gdma.o
obj-$(CONFIG_RALINK_SPI) 	+= ralink_spi_drv.o
obj-$(CONFIG_RALINK_I2C) 	+= ralink_i2c_drv.o
#obj-$(CONFIG_RALINK_PCM)	+= pcm/
#obj-$(CONFIG_RALINK_I2S)	+= i2s/
