#
# Makefile for the rtl8367m
#

EXTRA_CFLAGS += -D_LITTLE_ENDIAN

obj-$(CONFIG_RTL8367M)		+= rtl8370_asicdrv.o
obj-$(CONFIG_RTL8367M)		+= rtl8370_asicdrv_acl.o
obj-$(CONFIG_RTL8367M)		+= rtl8370_asicdrv_cputag.o
obj-$(CONFIG_RTL8367M)		+= rtl8370_asicdrv_dot1x.o
obj-$(CONFIG_RTL8367M)		+= rtl8370_asicdrv_eee.o
obj-$(CONFIG_RTL8367M)		+= rtl8370_asicdrv_eeelldp.o
obj-$(CONFIG_RTL8367M)		+= rtl8370_asicdrv_fc.o
obj-$(CONFIG_RTL8367M)		+= rtl8370_asicdrv_green.o
obj-$(CONFIG_RTL8367M)		+= rtl8370_asicdrv_igmp.o
obj-$(CONFIG_RTL8367M)		+= rtl8370_asicdrv_inbwctrl.o
obj-$(CONFIG_RTL8367M)		+= rtl8370_asicdrv_interrupt.o
obj-$(CONFIG_RTL8367M)		+= rtl8370_asicdrv_led.o
obj-$(CONFIG_RTL8367M)		+= rtl8370_asicdrv_lut.o
obj-$(CONFIG_RTL8367M)		+= rtl8370_asicdrv_meter.o
obj-$(CONFIG_RTL8367M)		+= rtl8370_asicdrv_mib.o
obj-$(CONFIG_RTL8367M)		+= rtl8370_asicdrv_mirror.o
obj-$(CONFIG_RTL8367M)		+= rtl8370_asicdrv_misc.o
obj-$(CONFIG_RTL8367M)		+= rtl8370_asicdrv_oam.o
obj-$(CONFIG_RTL8367M)		+= rtl8370_asicdrv_phy.o
obj-$(CONFIG_RTL8367M)		+= rtl8370_asicdrv_port.o
obj-$(CONFIG_RTL8367M)		+= rtl8370_asicdrv_portIsolation.o
obj-$(CONFIG_RTL8367M)		+= rtl8370_asicdrv_qos.o
obj-$(CONFIG_RTL8367M)		+= rtl8370_asicdrv_rldp.o
obj-$(CONFIG_RTL8367M)		+= rtl8370_asicdrv_rma.o
obj-$(CONFIG_RTL8367M)		+= rtl8370_asicdrv_rrcp.o
obj-$(CONFIG_RTL8367M)		+= rtl8370_asicdrv_scheduling.o
obj-$(CONFIG_RTL8367M)		+= rtl8370_asicdrv_specialCongest.o
obj-$(CONFIG_RTL8367M)		+= rtl8370_asicdrv_storm.o
obj-$(CONFIG_RTL8367M)		+= rtl8370_asicdrv_svlan.o
obj-$(CONFIG_RTL8367M)		+= rtl8370_asicdrv_trunking.o
obj-$(CONFIG_RTL8367M)		+= rtl8370_asicdrv_unknownMulticast.o
obj-$(CONFIG_RTL8367M)		+= rtl8370_asicdrv_vlan.o
obj-$(CONFIG_RTL8367M)		+= ralink_smi.o
obj-$(CONFIG_RTL8367M)		+= rtk_api.o
obj-$(CONFIG_RTL8367M)		+= rtl8367m_drv.o
