#!/bin/sh
#$1: dns server
set -e -o pipefail

dir="/etc/storage/dnsmasq-china-conf"
acc_china_file="accelerated-domains.china.conf"

if [ -z "$1" ] || [ ! -f $dir/$acc_china_file ]; then
	exit 1
else
	rm -f /tmp/$acc_china_file
	current_dns=`head -n1 $dir/$acc_china_file |cut -d '/' -f3`
	set_dns=$1
	if [ "$current_dns" != "$set_dns" ]; then
		sed "s|^\(server.*\)/[^/]*$|\1/${set_dns}|" $dir/$acc_china_file > /tmp/$acc_china_file
	fi
	mv -f /tmp/$acc_china_file $dir/$acc_china_file
	mtd_storage.sh save >/dev/null 2>&1
	restart_dhcpd
	restart_dns
	nvram set dnsmasq_china_conf_dns_server=$set_dns
	nvram commit
fi
