/* MiniDLNA Project
 * http://sourceforge.net/projects/minidlna/
 * (c) 2008-2009 Justin Maggard
 * generated by ./genconfig.sh on Вск Июл 22 02:26:39 KRAT 2012 */
#ifndef __CONFIG_H__
#define __CONFIG_H__

#define OS_NAME			"Linux"
#define OS_VERSION		"Linux/Cross_compiled"
#define OS_URL			"http://www.kernel.org/"

/* full path of the file database */
#define DEFAULT_DB_PATH		"/mnt/minidlna"

/* full path of the log directory */
#define DEFAULT_LOG_PATH	"/mnt/minidlna"

/* Comment the following line to use home made daemonize() func instead
 * of BSD daemon() */
#define USE_DAEMON

/* Enable if the system inotify.h exists.  Otherwise our own inotify.h will be used. */
#define HAVE_INOTIFY_H

/* Enable if the system iconv.h exists.  ID3 tag reading in various character sets will not work properly otherwise. */
#define HAVE_ICONV_H

/* Enable if the system libintl.h exists for NLS support. */
/*#define ENABLE_NLS*/

/* Enable ASUS-specific tweaks. */
#define ASUS_RT
/* Enable NETGEAR-specific tweaks. */
/*#define NETGEAR*/
/* Enable ReadyNAS-specific tweaks. */
/*#define READYNAS*/
/* Compile in TiVo support. */
#define TIVO_SUPPORT
/* Enable PnPX support. */
#define PNPX 0

#endif
