# Makefile for uClibc
#
# Copyright (C) 2000-2005 Erik Andersen <andersen@uclibc.org>
#
# Licensed under the LGPL v2.1, see the file COPYING.LIB in this tarball.
#

CSRC-y	:= brk.c clone.c mmap.c prctl.c sigaction.c

SSRC-y	:= __longjmp.S setjmp.S bsd-setjmp.S bsd-_setjmp.S	\
		sigrestorer.S syscall.S vfork.S
