/* PSG1208 */

#define BOARD_PID		"PSG1208"
#define BOARD_NAME		"PSG1208"
#define BOARD_DESC		"PHICOMM PSG1208 Wireless Router"
#define BOARD_VENDOR_NAME	"PHICOMM"
#define BOARD_VENDOR_URL	"http://www.phicomm.com/"
#define BOARD_MODEL_URL		"http://www.phicomm.com/"
#define BOARD_BOOT_TIME		25
#define BOARD_FLASH_TIME	120
#define BOARD_GPIO_BTN_RESET	1
#undef  BOARD_GPIO_BTN_WPS
#undef  BOARD_GPIO_LED_ALL
#define  BOARD_GPIO_LED_WIFI	72
#undef  BOARD_GPIO_LED_POWER
#undef  BOARD_GPIO_LED_LAN
#undef  BOARD_GPIO_LED_WAN
#undef  BOARD_GPIO_LED_USB
#undef  BOARD_GPIO_PWR_USB
#define BOARD_GPIO_LED_ROUTER	39
#define BOARD_HAS_5G_11AC	1
#define BOARD_NUM_ANT_5G_TX	2
#define BOARD_NUM_ANT_5G_RX	2
#define BOARD_NUM_ANT_2G_TX	2
#define BOARD_NUM_ANT_2G_RX	2
#define BOARD_NUM_ETH_LEDS	1
#define BOARD_HAS_EPHY_L1000	0
#define BOARD_HAS_EPHY_W1000	0

