#
# Makefile for the linux squashfs routines.
#
# the environment variables are not inherited since 2.6.23

obj-$(CONFIG_SQUASHFS) += squashfs.o
squashfs-y += inode.o
squashfs-y += uncomp.o
squashfs-y += LzmaDecode.o


