# $Id: Makefile,v 1.1.1.1 2007-05-25 06:50:17 bruce Exp $
# Makefile for the Sun Boot PROM interface library under
# Linux.
#

obj-y := init.o console.o printf.o  misc.o
#bootstr.o init.o misc.o segment.o console.o printf.o
