#!/bin/sh

func_start()
{
	echo "Start system tweak"
	# insert your custom code below
}

func_stop()
{
	echo "Stop system tweak"
	# insert your custom code below
}

case "$1" in
start)
	func_start
	;;
stop)
	func_stop
	;;
restart)
	func_stop
	func_start
	;;
*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
	;;
esac

