/* DIR-853-A3 */

#define BOARD_PID	"DIR-853-A3"
#define BOARD_NAME	"DIR-853-A3"
#define BOARD_DESC	"DIR-853-A3 Wireless Router"
#define BOARD_VENDOR_NAME	"DLINK"
#define BOARD_VENDOR_URL	"http://www.dlink.com/"
#define BOARD_MODEL_URL	"http://www.dlink.com/"
#define BOARD_BOOT_TIME			30
#define BOARD_FLASH_TIME		120
#define BOARD_GPIO_BTN_FN1		7
#undef	 BOARD_GPIO_BTN_FN2
#define BOARD_GPIO_BTN_RESET		8
#define BOARD_GPIO_BTN_WPS		18
#undef  BOARD_GPIO_LED_ALL
#undef  BOARD_GPIO_LED_WIFI
#define BOARD_GPIO_LED_SW2G		4
#define BOARD_GPIO_LED_SW5G		3
#define BOARD_GPIO_LED_POWER		14
#define BOARD_GPIO_LED_POWER_AMBER	13
#undef	BOARD_GPIO_LED_ROUTER
#undef  BOARD_GPIO_LED_LAN
#define BOARD_GPIO_LED_WAN		16
#define BOARD_GPIO_LED_WAN_AMBER	15
#define BOARD_GPIO_LED_USB		10
#undef  BOARD_GPIO_LED_USB2
#undef  BOARD_GPIO_PWR_USB
#define BOARD_HAS_5G_11AC		1
#define BOARD_NUM_ANT_5G_TX		2
#define BOARD_NUM_ANT_5G_RX		2
#define BOARD_NUM_ANT_2G_TX		2
#define BOARD_NUM_ANT_2G_RX		2
#define BOARD_NUM_ETH_LEDS		0
#define BOARD_HAS_EPHY_L1000		1
#define BOARD_HAS_EPHY_W1000		1
#define BOARD_NUM_UPHY_USB3		1
#define BOARD_USB_PORT_SWAP		0
