.TH UCLIBC-GCC 1
.SH NAME
uclibc-gcc \- Cross-compiler for uClibc
.SH SYNOPSIS
.B uclibc-gcc
[
.B options
]
.br
.B uclibc-ld
[
.B options
]
.SH DESCRIPTION
These programs are wrappers for
.B gcc
and
.B ld.
.SH BUGS
Probably.

.SH AUTHORS
Manuel Nova
.br
Manual page written by David Schleef <ds@schleef.org>
.SH SEE ALSO
.BR gcc (1),
.BR ld (1)
