#ifndef __RA_ETHREG_H__
#define __RA_ETHREG_H__

#include <asm/rt2880/rt_mmap.h>
#include <ralink/ralink_gpio.h>

/* Register Map Detail */
#define REG_SYSCFG0			(RALINK_SYSCTL_BASE + 0x10)
#define REG_SYSCFG1			(RALINK_SYSCTL_BASE + 0x14)
#define REG_RSTCTRL			(RALINK_SYSCTL_BASE + 0x34)

#if defined (CONFIG_RALINK_MT7628)
#define REG_AGPIOCFG			(RALINK_SYSCTL_BASE + 0x3C)
#endif

#if defined (CONFIG_RALINK_MT7621)
#define REG_CLK_CFG_0			(RALINK_SYSCTL_BASE + 0x2C)
#define REG_PAD_RGMII2_MDIO_CFG		(RALINK_SYSCTL_BASE + 0x58)
#define REG_MDIO_PHY_POLLING		(RALINK_ETH_SW_BASE + 0x0000)
#define REG_MDIO_PHY_CONTROL_0		(RALINK_ETH_SW_BASE + 0x0004)
#define REG_ETH_GE1_MAC_CONTROL		(RALINK_ETH_SW_BASE + 0x0100)
#define REG_ETH_GE1_MAC_STATUS		(RALINK_ETH_SW_BASE + 0x0108)
#define REG_ETH_GE2_MAC_CONTROL		(RALINK_ETH_SW_BASE + 0x0200)
#define REG_ETH_GE2_MAC_STATUS		(RALINK_ETH_SW_BASE + 0x0208)
#endif

#if defined (CONFIG_RALINK_MT7620)
#define REG_MDIO_PHY_POLLING		(RALINK_ETH_SW_BASE + 0x7000)
#define REG_MDIO_PHY_CONTROL_0		(RALINK_ETH_SW_BASE + 0x7004)
#endif

#if defined (CONFIG_RALINK_RT3052) || defined (CONFIG_RALINK_RT3352) || \
    defined (CONFIG_RALINK_RT5350) || defined (CONFIG_RALINK_MT7628)
#define REG_MDIO_PHY_CONTROL_0		(RALINK_ETH_SW_BASE + 0xC0)
#define REG_MDIO_PHY_CONTROL_1		(RALINK_ETH_SW_BASE + 0xC4)
#endif

#if defined (CONFIG_RALINK_RT3052) || defined (CONFIG_RALINK_RT3352)
#define REG_MDIO_PHY_POLLING		(RALINK_ETH_SW_BASE + 0xC8)
#endif

#if defined (CONFIG_RALINK_RT3883)
#define REG_MDIO_PHY_CONTROL_0		(RALINK_FRAME_ENGINE_BASE + 0x00)
#define REG_MDIO_PHY_POLLING		(RALINK_FRAME_ENGINE_BASE + 0x04)
#endif

/* FE_INT_STATUS */
#if defined (CONFIG_RALINK_RT5350) || defined (CONFIG_RALINK_MT7628) || \
    defined (CONFIG_RALINK_MT7620) || defined (CONFIG_RALINK_MT7621)

#define RX_COHERENT			BIT(31)
#define RX_DLY_INT			BIT(30)
#define TX_COHERENT			BIT(29)
#define TX_DLY_INT			BIT(28)
#define RX_DONE_INT1			BIT(17)
#define RX_DONE_INT0			BIT(16)
#define TX_DONE_INT3			BIT(3)
#define TX_DONE_INT2			BIT(2)
#define TX_DONE_INT1			BIT(1)
#define TX_DONE_INT0			BIT(0)
#if defined (CONFIG_RALINK_MT7621)
#define RLS_COHERENT			BIT(29)
#define RLS_DLY_INT			BIT(28)
#define RLS_DONE_INT			BIT(0)
#endif

#else

#define CNT_PPE_AF			BIT(31)
#define CNT_GDM2_AF			BIT(30)
#define CNT_GDM1_AF			BIT(29)
#define PSE_P2_FC			BIT(26)
#define GDM_CRC_DROP			BIT(25)
#define PSE_BUF_DROP			BIT(24)
#define GDM_OTHER_DROP			BIT(23)
#define PSE_P1_FC			BIT(22)
#define PSE_P0_FC			BIT(21)
#define PSE_FQ_EMPTY			BIT(20)
#define GE1_STA_CHG			BIT(18)
#define TX_COHERENT			BIT(17)
#define RX_COHERENT			BIT(16)
#define TX_DONE_INT3			BIT(11)
#define TX_DONE_INT2			BIT(10)
#define TX_DONE_INT1			BIT(9)
#define TX_DONE_INT0			BIT(8)
#define RX_DONE_INT1			RX_DONE_INT0
#define RX_DONE_INT0			BIT(2)
#define TX_DLY_INT			BIT(1)
#define RX_DLY_INT			BIT(0)

#endif

/* aggregate up to 4 INT, max delay 40us */
#define FE_DLY_INIT_VALUE		0x84028402

#if defined (CONFIG_RAETH_QDMA)
#if defined (CONFIG_RAETH_QDMATX_QDMARX)
/* QDMA P5 handle TX and RX path */
#define QFE_INT_INIT_VALUE		(RLS_DLY_INT | RX_DLY_INT)
#define QFE_INT_MASK_TX_RX		(RLS_DLY_INT | RX_DLY_INT)
#define QFE_INT_MASK_TX			(RLS_DLY_INT)
#define QFE_INT_MASK_RX			(RX_DLY_INT)
/* PDMA P0 is not used */
#define FE_INT_INIT_VALUE		0
#define FE_INT_MASK_TX_RX		0
#define FE_INT_MASK_TX			0
#define FE_INT_MASK_RX			0
#else
/* QDMA P5 handle TX path only */
#define QFE_INT_INIT_VALUE		(RLS_DLY_INT)
#define QFE_INT_MASK_TX_RX		(RLS_DLY_INT)
#define QFE_INT_MASK_TX			(RLS_DLY_INT)
#define QFE_INT_MASK_RX			0
/* PDMA P0 handle RX path only */
#define FE_INT_INIT_VALUE		(RX_DLY_INT)
#define FE_INT_MASK_TX_RX		(RX_DLY_INT)
#define FE_INT_MASK_TX			0
#define FE_INT_MASK_RX			(RX_DLY_INT)
#endif
#else
/* PDMA P0 handle TX and RX path */
#define FE_INT_INIT_VALUE		(TX_DLY_INT | RX_DLY_INT)
#define FE_INT_MASK_TX_RX		(TX_DLY_INT | RX_DLY_INT)
#define FE_INT_MASK_TX			(TX_DLY_INT)
#define FE_INT_MASK_RX			(RX_DLY_INT)
#endif


/* FE_INT_STATUS2 */
#if defined (CONFIG_RALINK_MT7620)
#define PPE_MIB_AF			BIT(31)
#define GDM_MIB_AF			BIT(29)
#define FE_INT_INIT2_VALUE		0
#elif defined (CONFIG_RALINK_MT7621)
#define PPE_MIB_AF			BIT(31)
#define GE2_MIB_AF			BIT(29)
#define GE1_MIB_AF			BIT(28)
#define GE2_LINK_INT			BIT(25)
#define GE1_LINK_INT			BIT(24)
#define CDM_TSO_ALIGN			BIT(14)
#define CDM_TSO_ILLEGAL			BIT(13)
#define CDM_TSO_FAIL			BIT(12)
#if defined (CONFIG_GE2_INTERNAL_GPHY_P0) || defined (CONFIG_GE2_RGMII_AN) || \
    defined (CONFIG_GE2_INTERNAL_GPHY_P4)
#define FE_INT_INIT2_VALUE		(GE2_LINK_INT)
#else
#define FE_INT_INIT2_VALUE		0
#endif
#endif


/* Register Categories Definition */

#if defined (CONFIG_RALINK_RT5350) || defined (CONFIG_RALINK_MT7628)

#define RAPDMA_OFFSET			0x0800
#define TX_BASE_PTR0			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x000)
#define TX_MAX_CNT0			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x004)
#define TX_CTX_IDX0			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x008)
#define TX_DTX_IDX0			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x00C)

#define TX_BASE_PTR1			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x010)
#define TX_MAX_CNT1			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x014)
#define TX_CTX_IDX1			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x018)
#define TX_DTX_IDX1			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x01C)

#define TX_BASE_PTR2			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x020)
#define TX_MAX_CNT2			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x024)
#define TX_CTX_IDX2			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x028)
#define TX_DTX_IDX2			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x02C)

#define TX_BASE_PTR3			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x030)
#define TX_MAX_CNT3			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x034)
#define TX_CTX_IDX3			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x038)
#define TX_DTX_IDX3			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x03C)

#define RX_BASE_PTR0			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x100)
#define RX_MAX_CNT0			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x104)
#define RX_CALC_IDX0			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x108)
#define RX_DRX_IDX0			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x10C)

#define RX_BASE_PTR1			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x110)
#define RX_MAX_CNT1			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x114)
#define RX_CALC_IDX1			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x118)
#define RX_DRX_IDX1			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x11C)

#define PDMA_INFO			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x200)
#define PDMA_GLO_CFG			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x204)
#define PDMA_RST_CFG			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x208)
#define DLY_INT_CFG			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x20C)
#define FREEQ_THRES			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x210)
#define FE_INT_STATUS			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x220)
#define FE_INT_ENABLE			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x228)
#define PDMA_SCH_CFG			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x280)
#define PDMA_WRR_CFG			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x284)

#define RASDM_OFFSET			0x0C00
#define SDM_CON				(RALINK_FRAME_ENGINE_BASE+RASDM_OFFSET+0x00)  //Switch DMA configuration
#define SDM_RRING			(RALINK_FRAME_ENGINE_BASE+RASDM_OFFSET+0x04)  //Switch DMA Rx Ring
#define SDM_TRING			(RALINK_FRAME_ENGINE_BASE+RASDM_OFFSET+0x08)  //Switch DMA Tx Ring
#define SDM_MAC_ADRL			(RALINK_FRAME_ENGINE_BASE+RASDM_OFFSET+0x0C)  //Switch MAC address LSB
#define SDM_MAC_ADRH			(RALINK_FRAME_ENGINE_BASE+RASDM_OFFSET+0x10)  //Switch MAC Address MSB
#define SDM_TPCNT			(RALINK_FRAME_ENGINE_BASE+RASDM_OFFSET+0x100) //Switch DMA Tx packet count
#define SDM_TBCNT			(RALINK_FRAME_ENGINE_BASE+RASDM_OFFSET+0x104) //Switch DMA Tx byte count
#define SDM_RPCNT			(RALINK_FRAME_ENGINE_BASE+RASDM_OFFSET+0x108) //Switch DMA rx packet count
#define SDM_RBCNT			(RALINK_FRAME_ENGINE_BASE+RASDM_OFFSET+0x10C) //Switch DMA rx byte count
#define SDM_CS_ERR			(RALINK_FRAME_ENGINE_BASE+RASDM_OFFSET+0x110) //Switch DMA rx checksum error count

#define SDM_TCI_81XX			BIT(20)
#define SDM_UDPCS			BIT(18)
#define SDM_TCPCS			BIT(17)
#define SDM_IPCS			BIT(16)

#elif defined (CONFIG_RALINK_MT7620) || defined (CONFIG_RALINK_MT7621)

#define FE_GLO_CFG			(RALINK_FRAME_ENGINE_BASE + 0x00)
#define FE_RST_GLO			(RALINK_FRAME_ENGINE_BASE + 0x04)
#define FE_INT_STATUS2			(RALINK_FRAME_ENGINE_BASE + 0x08)
#define FE_INT_ENABLE2			(RALINK_FRAME_ENGINE_BASE + 0x0C)
#define FE_FOE_TS_T			(RALINK_FRAME_ENGINE_BASE + 0x10)
#define FE_IPV6_EXT			(RALINK_FRAME_ENGINE_BASE + 0x14)

#define RAPDMA_OFFSET			0x0800
#define TX_BASE_PTR0			(RALINK_FRAME_ENGINE_BASE + RAPDMA_OFFSET+0x000)
#define TX_MAX_CNT0			(RALINK_FRAME_ENGINE_BASE + RAPDMA_OFFSET+0x004)
#define TX_CTX_IDX0			(RALINK_FRAME_ENGINE_BASE + RAPDMA_OFFSET+0x008)
#define TX_DTX_IDX0			(RALINK_FRAME_ENGINE_BASE + RAPDMA_OFFSET+0x00C)

#define TX_BASE_PTR1			(RALINK_FRAME_ENGINE_BASE + RAPDMA_OFFSET+0x010)
#define TX_MAX_CNT1			(RALINK_FRAME_ENGINE_BASE + RAPDMA_OFFSET+0x014)
#define TX_CTX_IDX1			(RALINK_FRAME_ENGINE_BASE + RAPDMA_OFFSET+0x018)
#define TX_DTX_IDX1			(RALINK_FRAME_ENGINE_BASE + RAPDMA_OFFSET+0x01C)

#define TX_BASE_PTR2			(RALINK_FRAME_ENGINE_BASE + RAPDMA_OFFSET+0x020)
#define TX_MAX_CNT2			(RALINK_FRAME_ENGINE_BASE + RAPDMA_OFFSET+0x024)
#define TX_CTX_IDX2			(RALINK_FRAME_ENGINE_BASE + RAPDMA_OFFSET+0x028)
#define TX_DTX_IDX2			(RALINK_FRAME_ENGINE_BASE + RAPDMA_OFFSET+0x02C)

#define TX_BASE_PTR3			(RALINK_FRAME_ENGINE_BASE + RAPDMA_OFFSET+0x030)
#define TX_MAX_CNT3			(RALINK_FRAME_ENGINE_BASE + RAPDMA_OFFSET+0x034)
#define TX_CTX_IDX3			(RALINK_FRAME_ENGINE_BASE + RAPDMA_OFFSET+0x038)
#define TX_DTX_IDX3			(RALINK_FRAME_ENGINE_BASE + RAPDMA_OFFSET+0x03C)

#define RX_BASE_PTR0			(RALINK_FRAME_ENGINE_BASE + RAPDMA_OFFSET+0x100)
#define RX_MAX_CNT0			(RALINK_FRAME_ENGINE_BASE + RAPDMA_OFFSET+0x104)
#define RX_CALC_IDX0			(RALINK_FRAME_ENGINE_BASE + RAPDMA_OFFSET+0x108)
#define RX_DRX_IDX0			(RALINK_FRAME_ENGINE_BASE + RAPDMA_OFFSET+0x10C)

#define RX_BASE_PTR1			(RALINK_FRAME_ENGINE_BASE + RAPDMA_OFFSET+0x110)
#define RX_MAX_CNT1			(RALINK_FRAME_ENGINE_BASE + RAPDMA_OFFSET+0x114)
#define RX_CALC_IDX1			(RALINK_FRAME_ENGINE_BASE + RAPDMA_OFFSET+0x118)
#define RX_DRX_IDX1			(RALINK_FRAME_ENGINE_BASE + RAPDMA_OFFSET+0x11C)

#define PDMA_INFO			(RALINK_FRAME_ENGINE_BASE + RAPDMA_OFFSET+0x200)
#define PDMA_GLO_CFG			(RALINK_FRAME_ENGINE_BASE + RAPDMA_OFFSET+0x204)
#define PDMA_RST_CFG			(RALINK_FRAME_ENGINE_BASE + RAPDMA_OFFSET+0x208)
#define DLY_INT_CFG			(RALINK_FRAME_ENGINE_BASE + RAPDMA_OFFSET+0x20C)
#define FREEQ_THRES			(RALINK_FRAME_ENGINE_BASE + RAPDMA_OFFSET+0x210)
#define FE_INT_STATUS			(RALINK_FRAME_ENGINE_BASE + RAPDMA_OFFSET+0x220)
#define FE_INT_ENABLE			(RALINK_FRAME_ENGINE_BASE + RAPDMA_OFFSET+0x228)
#define SCH_Q01_CFG			(RALINK_FRAME_ENGINE_BASE + RAPDMA_OFFSET+0x280)
#define SCH_Q23_CFG			(RALINK_FRAME_ENGINE_BASE + RAPDMA_OFFSET+0x284)

#if defined (CONFIG_RALINK_MT7621)
#define RAPSE_OFFSET			0x0100
#define PSE_FQFC_CFG			(RALINK_FRAME_ENGINE_BASE + RAPSE_OFFSET + 0x00)
#define PSE_IQ_REV1			(RALINK_FRAME_ENGINE_BASE + RAPSE_OFFSET + 0x08)
#define PSE_IQ_REV2			(RALINK_FRAME_ENGINE_BASE + RAPSE_OFFSET + 0x0C)
#define PSE_IQ_STA1			(RALINK_FRAME_ENGINE_BASE + RAPSE_OFFSET + 0x10)
#define PSE_IQ_STA2			(RALINK_FRAME_ENGINE_BASE + RAPSE_OFFSET + 0x14)
#define PSE_OQ_STA1			(RALINK_FRAME_ENGINE_BASE + RAPSE_OFFSET + 0x18)
#define PSE_OQ_STA2			(RALINK_FRAME_ENGINE_BASE + RAPSE_OFFSET + 0x1C)
#define PSE_MIR_PORT			(RALINK_FRAME_ENGINE_BASE + RAPSE_OFFSET + 0x20)

#define RACDMP_OFFSET			0x0400
#define CDMP_IG_CTRL			(RALINK_FRAME_ENGINE_BASE + RACDMP_OFFSET + 0x00)
#define CDMP_EG_CTRL			(RALINK_FRAME_ENGINE_BASE + RACDMP_OFFSET + 0x04)
#define CDMP_PPPOE_GEN			(RALINK_FRAME_ENGINE_BASE + RACDMP_OFFSET + 0x08)
#define CDMA_CSG_CFG			CDMP_IG_CTRL // fake

#define RACDMQ_OFFSET			0x1400
#define CDMQ_IG_CTRL			(RALINK_FRAME_ENGINE_BASE + RACDMQ_OFFSET + 0x00)
#define CDMQ_EG_CTRL			(RALINK_FRAME_ENGINE_BASE + RACDMQ_OFFSET + 0x04)
#define CDMQ_PPPOE_GEN			(RALINK_FRAME_ENGINE_BASE + RACDMQ_OFFSET + 0x08)

#if defined (CONFIG_RAETH_SWAP_GDMA)
#define RAGDMA2_OFFSET			0x0500
#define RAGDMA1_OFFSET			0x1500
#else
#define RAGDMA1_OFFSET			0x0500
#define RAGDMA2_OFFSET			0x1500
#endif

#define GDMA1_FWD_CFG			(RALINK_FRAME_ENGINE_BASE + RAGDMA1_OFFSET + 0x00)
#define GDMA1_SHPR_CFG			(RALINK_FRAME_ENGINE_BASE + RAGDMA1_OFFSET + 0x04)
#define GDMA1_MAC_ADRL			(RALINK_FRAME_ENGINE_BASE + RAGDMA1_OFFSET + 0x08)
#define GDMA1_MAC_ADRH			(RALINK_FRAME_ENGINE_BASE + RAGDMA1_OFFSET + 0x0C)
#define GDMA1_VLAN_GEN			(RALINK_FRAME_ENGINE_BASE + RAGDMA1_OFFSET + 0x10)

#define GDMA2_FWD_CFG			(RALINK_FRAME_ENGINE_BASE + RAGDMA2_OFFSET + 0x00)
#define GDMA2_SHPR_CFG			(RALINK_FRAME_ENGINE_BASE + RAGDMA2_OFFSET + 0x04)
#define GDMA2_MAC_ADRL			(RALINK_FRAME_ENGINE_BASE + RAGDMA2_OFFSET + 0x08)
#define GDMA2_MAC_ADRH			(RALINK_FRAME_ENGINE_BASE + RAGDMA2_OFFSET + 0x0C)
#define GDMA2_VLAN_GEN			(RALINK_FRAME_ENGINE_BASE + RAGDMA2_OFFSET + 0x10)

#define RACMTABLE_OFFSET		0x2000
#define PPE_AC_BCNT_GROUP0		(RALINK_FRAME_ENGINE_BASE+RACMTABLE_OFFSET+0x000) // 64 bits
#define PPE_AC_PCNT_GROUP0		(RALINK_FRAME_ENGINE_BASE+RACMTABLE_OFFSET+0x008)
#define PPE_MTR_GROUP0			(RALINK_FRAME_ENGINE_BASE+RACMTABLE_OFFSET+0x00C)
#define PPE_AC_BCNT_GROUP1		(RALINK_FRAME_ENGINE_BASE+RACMTABLE_OFFSET+0x010) // 64 bits
#define PPE_AC_PCNT_GROUP1		(RALINK_FRAME_ENGINE_BASE+RACMTABLE_OFFSET+0x018)
#define PPE_MTR_GROUP1			(RALINK_FRAME_ENGINE_BASE+RACMTABLE_OFFSET+0x01C)
#define PPE_AC_BCNT_GROUP2		(RALINK_FRAME_ENGINE_BASE+RACMTABLE_OFFSET+0x020) // 64 bits
#define PPE_AC_PCNT_GROUP2		(RALINK_FRAME_ENGINE_BASE+RACMTABLE_OFFSET+0x028)
#define PPE_MTR_GROUP2			(RALINK_FRAME_ENGINE_BASE+RACMTABLE_OFFSET+0x02C)
#define PPE_AC_BCNT_GROUP63		(RALINK_FRAME_ENGINE_BASE+RACMTABLE_OFFSET+0x3F0) // 64 bits
#define PPE_AC_PCNT_GROUP63		(RALINK_FRAME_ENGINE_BASE+RACMTABLE_OFFSET+0x3F8)
#define PPE_MTR_GROUP63			(RALINK_FRAME_ENGINE_BASE+RACMTABLE_OFFSET+0x3FC)

#if defined (CONFIG_RAETH_SWAP_GDMA)
#define GDMA2_MIB_OFFSET		(RACMTABLE_OFFSET+0x400)
#define GDMA1_MIB_OFFSET		(RACMTABLE_OFFSET+0x440)
#else
#define GDMA1_MIB_OFFSET		(RACMTABLE_OFFSET+0x400)
#define GDMA2_MIB_OFFSET		(RACMTABLE_OFFSET+0x440)
#endif

#define GDMA1_RX_GBCNT			(RALINK_FRAME_ENGINE_BASE+GDMA1_MIB_OFFSET+0x00) // 64 bits
#define GDMA1_RX_GPCNT			(RALINK_FRAME_ENGINE_BASE+GDMA1_MIB_OFFSET+0x08)
#define GDMA1_RX_OERCNT			(RALINK_FRAME_ENGINE_BASE+GDMA1_MIB_OFFSET+0x10)
#define GDMA1_RX_FERCNT			(RALINK_FRAME_ENGINE_BASE+GDMA1_MIB_OFFSET+0x14)
#define GDMA1_RX_SERCNT			(RALINK_FRAME_ENGINE_BASE+GDMA1_MIB_OFFSET+0x18)
#define GDMA1_RX_LERCNT			(RALINK_FRAME_ENGINE_BASE+GDMA1_MIB_OFFSET+0x1C)
#define GDMA1_RX_CERCNT			(RALINK_FRAME_ENGINE_BASE+GDMA1_MIB_OFFSET+0x20)
#define GDMA1_RX_FCCNT			(RALINK_FRAME_ENGINE_BASE+GDMA1_MIB_OFFSET+0x24)
#define GDMA1_TX_SKIPCNT		(RALINK_FRAME_ENGINE_BASE+GDMA1_MIB_OFFSET+0x28)
#define GDMA1_TX_COLCNT			(RALINK_FRAME_ENGINE_BASE+GDMA1_MIB_OFFSET+0x2C)
#define GDMA1_TX_GBCNT			(RALINK_FRAME_ENGINE_BASE+GDMA1_MIB_OFFSET+0x30) // 64 bits
#define GDMA1_TX_GPCNT			(RALINK_FRAME_ENGINE_BASE+GDMA1_MIB_OFFSET+0x38)

#define GDMA2_RX_GBCNT			(RALINK_FRAME_ENGINE_BASE+GDMA2_MIB_OFFSET+0x00) // 64 bits
#define GDMA2_RX_GPCNT			(RALINK_FRAME_ENGINE_BASE+GDMA2_MIB_OFFSET+0x08)
#define GDMA2_RX_OERCNT			(RALINK_FRAME_ENGINE_BASE+GDMA2_MIB_OFFSET+0x10)
#define GDMA2_RX_FERCNT			(RALINK_FRAME_ENGINE_BASE+GDMA2_MIB_OFFSET+0x14)
#define GDMA2_RX_SERCNT			(RALINK_FRAME_ENGINE_BASE+GDMA2_MIB_OFFSET+0x18)
#define GDMA2_RX_LERCNT			(RALINK_FRAME_ENGINE_BASE+GDMA2_MIB_OFFSET+0x1C)
#define GDMA2_RX_CERCNT			(RALINK_FRAME_ENGINE_BASE+GDMA2_MIB_OFFSET+0x20)
#define GDMA2_RX_FCCNT			(RALINK_FRAME_ENGINE_BASE+GDMA2_MIB_OFFSET+0x24)
#define GDMA2_TX_SKIPCNT		(RALINK_FRAME_ENGINE_BASE+GDMA2_MIB_OFFSET+0x28)
#define GDMA2_TX_COLCNT			(RALINK_FRAME_ENGINE_BASE+GDMA2_MIB_OFFSET+0x2C)
#define GDMA2_TX_GBCNT			(RALINK_FRAME_ENGINE_BASE+GDMA2_MIB_OFFSET+0x30) // 64 bits
#define GDMA2_TX_GPCNT			(RALINK_FRAME_ENGINE_BASE+GDMA2_MIB_OFFSET+0x38)

#else /* MT7620 */
#define RACDMA_OFFSET			0x0400
#define CDMA_CSG_CFG			(RALINK_FRAME_ENGINE_BASE + RACDMA_OFFSET + 0x00)
#define CDMA_PPPOE_SID0			(RALINK_FRAME_ENGINE_BASE + RACDMA_OFFSET + 0x10)
#define CDMA_VLAN_ID0			(RALINK_FRAME_ENGINE_BASE + RACDMA_OFFSET + 0x30)

#define RAPSE_OFFSET			0x0500
#define PSE_FQFC_CFG			(RALINK_FRAME_ENGINE_BASE + RAPSE_OFFSET + 0x00)
#define PSE_IQ_CFG			(RALINK_FRAME_ENGINE_BASE + RAPSE_OFFSET + 0x04)
#define PSE_QUE_STA			(RALINK_FRAME_ENGINE_BASE + RAPSE_OFFSET + 0x08)

#define RAGDMA1_OFFSET			0x0600
#define GDMA1_FWD_CFG			(RALINK_FRAME_ENGINE_BASE + RAGDMA1_OFFSET + 0x00)
#define GDMA1_SHPR_CFG			(RALINK_FRAME_ENGINE_BASE + RAGDMA1_OFFSET + 0x04)

#define SMACCR0				(RALINK_ETH_SW_BASE + 0x3FE4)
#define SMACCR1				(RALINK_ETH_SW_BASE + 0x3FE8)
#define CKGCR				(RALINK_ETH_SW_BASE + 0x3FF0)

#define RACMTABLE_OFFSET		0x1000
#define PPE_AC_BCNT_GROUP0		(RALINK_FRAME_ENGINE_BASE+RACMTABLE_OFFSET+0x000)
#define PPE_AC_PCNT_GROUP0		(RALINK_FRAME_ENGINE_BASE+RACMTABLE_OFFSET+0x004)
#define PPE_AC_BCNT_GROUP1		(RALINK_FRAME_ENGINE_BASE+RACMTABLE_OFFSET+0x008)
#define PPE_AC_PCNT_GROUP1		(RALINK_FRAME_ENGINE_BASE+RACMTABLE_OFFSET+0x00C)
#define PPE_AC_BCNT_GROUP2		(RALINK_FRAME_ENGINE_BASE+RACMTABLE_OFFSET+0x010)
#define PPE_AC_PCNT_GROUP2		(RALINK_FRAME_ENGINE_BASE+RACMTABLE_OFFSET+0x014)
#define PPE_AC_BCNT_GROUP63		(RALINK_FRAME_ENGINE_BASE+RACMTABLE_OFFSET+0x1F8)
#define PPE_AC_PCNT_GROUP63		(RALINK_FRAME_ENGINE_BASE+RACMTABLE_OFFSET+0x1FC)

/* CPU port P6 */
#define GDMA1_TX_GBCNT			(RALINK_FRAME_ENGINE_BASE+RACMTABLE_OFFSET+0x300)
#define GDMA1_TX_GPCNT			(RALINK_FRAME_ENGINE_BASE+RACMTABLE_OFFSET+0x304)
#define GDMA1_TX_SKIPCNT		(RALINK_FRAME_ENGINE_BASE+RACMTABLE_OFFSET+0x308)
#define GDMA1_TX_COLCNT			(RALINK_FRAME_ENGINE_BASE+RACMTABLE_OFFSET+0x30C)
#define GDMA1_RX_GBCNT			(RALINK_FRAME_ENGINE_BASE+RACMTABLE_OFFSET+0x320)
#define GDMA1_RX_GPCNT			(RALINK_FRAME_ENGINE_BASE+RACMTABLE_OFFSET+0x324)
#define GDMA1_RX_OERCNT			(RALINK_FRAME_ENGINE_BASE+RACMTABLE_OFFSET+0x328)
#define GDMA1_RX_FERCNT			(RALINK_FRAME_ENGINE_BASE+RACMTABLE_OFFSET+0x32C)
#define GDMA1_RX_SERCNT			(RALINK_FRAME_ENGINE_BASE+RACMTABLE_OFFSET+0x330)
#define GDMA1_RX_LERCNT			(RALINK_FRAME_ENGINE_BASE+RACMTABLE_OFFSET+0x334)
#define GDMA1_RX_CERCNT			(RALINK_FRAME_ENGINE_BASE+RACMTABLE_OFFSET+0x338)
#define GDMA1_RX_FCCNT			(RALINK_FRAME_ENGINE_BASE+RACMTABLE_OFFSET+0x33C)

/* PPE port P7 */
#define GDMA2_TX_GBCNT			(RALINK_FRAME_ENGINE_BASE+RACMTABLE_OFFSET+0x340)
#define GDMA2_TX_GPCNT			(RALINK_FRAME_ENGINE_BASE+RACMTABLE_OFFSET+0x344)
#define GDMA2_TX_SKIPCNT		(RALINK_FRAME_ENGINE_BASE+RACMTABLE_OFFSET+0x348)
#define GDMA2_TX_COLCNT			(RALINK_FRAME_ENGINE_BASE+RACMTABLE_OFFSET+0x34C)
#define GDMA2_RX_GBCNT			(RALINK_FRAME_ENGINE_BASE+RACMTABLE_OFFSET+0x360)
#define GDMA2_RX_GPCNT			(RALINK_FRAME_ENGINE_BASE+RACMTABLE_OFFSET+0x364)
#define GDMA2_RX_OERCNT			(RALINK_FRAME_ENGINE_BASE+RACMTABLE_OFFSET+0x368)
#define GDMA2_RX_FERCNT			(RALINK_FRAME_ENGINE_BASE+RACMTABLE_OFFSET+0x36C)
#define GDMA2_RX_SERCNT			(RALINK_FRAME_ENGINE_BASE+RACMTABLE_OFFSET+0x370)
#define GDMA2_RX_LERCNT			(RALINK_FRAME_ENGINE_BASE+RACMTABLE_OFFSET+0x374)
#define GDMA2_RX_CERCNT			(RALINK_FRAME_ENGINE_BASE+RACMTABLE_OFFSET+0x378)
#define GDMA2_RX_FCCNT			(RALINK_FRAME_ENGINE_BASE+RACMTABLE_OFFSET+0x37C)

#endif

#else /* RT3052, RT3352, RT3883 */

#define MDIO_ACCESS			(RALINK_FRAME_ENGINE_BASE+0x00)
#define MDIO_CFG			(RALINK_FRAME_ENGINE_BASE+0x04)
#define FE_GLO_CFG			(RALINK_FRAME_ENGINE_BASE+0x08)
#define FE_RST_GLO			(RALINK_FRAME_ENGINE_BASE+0x0C)
#define FE_INT_STATUS			(RALINK_FRAME_ENGINE_BASE+0x10)
#define FE_INT_ENABLE			(RALINK_FRAME_ENGINE_BASE+0x14)
#define MDIO_CFG2			(RALINK_FRAME_ENGINE_BASE+0x18) //Original:FC_DROP_STA
#define FE_FOE_TS_T			(RALINK_FRAME_ENGINE_BASE+0x1C)

#if defined (CONFIG_RAETH_SWAP_GDMA)
#define RAGDMA2_OFFSET			0x0020
#define RAGDMA1_OFFSET			0x0060
#else
#define RAGDMA1_OFFSET			0x0020
#define RAGDMA2_OFFSET			0x0060
#endif

#define GDMA1_FWD_CFG			(RALINK_FRAME_ENGINE_BASE+RAGDMA1_OFFSET+0x00)
#define GDMA1_SCH_CFG			(RALINK_FRAME_ENGINE_BASE+RAGDMA1_OFFSET+0x04)
#define GDMA1_SHPR_CFG			(RALINK_FRAME_ENGINE_BASE+RAGDMA1_OFFSET+0x08)
#define GDMA1_MAC_ADRL			(RALINK_FRAME_ENGINE_BASE+RAGDMA1_OFFSET+0x0C)
#define GDMA1_MAC_ADRH			(RALINK_FRAME_ENGINE_BASE+RAGDMA1_OFFSET+0x10)

#define GDMA2_FWD_CFG			(RALINK_FRAME_ENGINE_BASE+RAGDMA2_OFFSET+0x00)
#define GDMA2_SCH_CFG			(RALINK_FRAME_ENGINE_BASE+RAGDMA2_OFFSET+0x04)
#define GDMA2_SHPR_CFG			(RALINK_FRAME_ENGINE_BASE+RAGDMA2_OFFSET+0x08)
#define GDMA2_MAC_ADRL			(RALINK_FRAME_ENGINE_BASE+RAGDMA2_OFFSET+0x0C)
#define GDMA2_MAC_ADRH			(RALINK_FRAME_ENGINE_BASE+RAGDMA2_OFFSET+0x10)

#define RAPSE_OFFSET			0x0040
#define PSE_FQ_CFG			(RALINK_FRAME_ENGINE_BASE+RAPSE_OFFSET+0x00)
#define CDMA_FC_CFG			(RALINK_FRAME_ENGINE_BASE+RAPSE_OFFSET+0x04)
#define GDMA1_FC_CFG			(RALINK_FRAME_ENGINE_BASE+RAPSE_OFFSET+0x08)
#define GDMA2_FC_CFG			(RALINK_FRAME_ENGINE_BASE+RAPSE_OFFSET+0x0C)
#define CDMA_OQ_STA			(RALINK_FRAME_ENGINE_BASE+RAPSE_OFFSET+0x10)
#define GDMA1_OQ_STA			(RALINK_FRAME_ENGINE_BASE+RAPSE_OFFSET+0x14)
#define GDMA2_OQ_STA			(RALINK_FRAME_ENGINE_BASE+RAPSE_OFFSET+0x18)
#define PSE_IQ_STA			(RALINK_FRAME_ENGINE_BASE+RAPSE_OFFSET+0x1C)

#define RACDMA_OFFSET			0x0080
#define CDMA_CSG_CFG			(RALINK_FRAME_ENGINE_BASE+RACDMA_OFFSET+0x00)
#define CDMA_SCH_CFG			(RALINK_FRAME_ENGINE_BASE+RACDMA_OFFSET+0x04)
#define CDMA_PPPOE_SID0			(RALINK_FRAME_ENGINE_BASE+RACDMA_OFFSET+0x08)
#define CDMA_VLAN_ID0			(RALINK_FRAME_ENGINE_BASE+RACDMA_OFFSET+0x28)

#define RAPDMA_OFFSET			0x0100
#define PDMA_GLO_CFG			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x00)
#define PDMA_RST_CFG			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x04)
#define PDMA_SCH_CFG			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x08)

#define DLY_INT_CFG			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x0C)

#define TX_BASE_PTR0			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x10)
#define TX_MAX_CNT0			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x14)
#define TX_CTX_IDX0			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x18)
#define TX_DTX_IDX0			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x1C)

#define TX_BASE_PTR1			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x20)
#define TX_MAX_CNT1			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x24)
#define TX_CTX_IDX1			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x28)
#define TX_DTX_IDX1			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x2C)

#define TX_BASE_PTR2			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x40)
#define TX_MAX_CNT2			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x44)
#define TX_CTX_IDX2			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x48)
#define TX_DTX_IDX2			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x4C)

#define TX_BASE_PTR3			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x50)
#define TX_MAX_CNT3			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x54)
#define TX_CTX_IDX3			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x58)
#define TX_DTX_IDX3			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x5C)

#define RX_BASE_PTR0			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x30)
#define RX_MAX_CNT0			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x34)
#define RX_CALC_IDX0			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x38)
#define RX_DRX_IDX0			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0x3C)

#define PDMA_FC_CFG			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0xf0)
#define SCH_Q01_CFG			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0xf4)
#define SCH_Q23_CFG			(RALINK_FRAME_ENGINE_BASE+RAPDMA_OFFSET+0xf8)

#define RACMTABLE_OFFSET		0x0400

#if defined (CONFIG_RAETH_SWAP_GDMA)
#define GDMA2_MIB_OFFSET		(RACMTABLE_OFFSET+0x300)
#define GDMA1_MIB_OFFSET		(RACMTABLE_OFFSET+0x340)
#else
#define GDMA1_MIB_OFFSET		(RACMTABLE_OFFSET+0x300)
#define GDMA2_MIB_OFFSET		(RACMTABLE_OFFSET+0x340)
#endif

#define GDMA1_TX_GBCNT			(RALINK_FRAME_ENGINE_BASE+GDMA1_MIB_OFFSET+0x00)
#define GDMA1_TX_GPCNT			(RALINK_FRAME_ENGINE_BASE+GDMA1_MIB_OFFSET+0x04)
#define GDMA1_TX_SKIPCNT		(RALINK_FRAME_ENGINE_BASE+GDMA1_MIB_OFFSET+0x08)
#define GDMA1_TX_COLCNT			(RALINK_FRAME_ENGINE_BASE+GDMA1_MIB_OFFSET+0x0C)
#define GDMA1_RX_GBCNT			(RALINK_FRAME_ENGINE_BASE+GDMA1_MIB_OFFSET+0x20)
#define GDMA1_RX_GPCNT			(RALINK_FRAME_ENGINE_BASE+GDMA1_MIB_OFFSET+0x24)
#define GDMA1_RX_OERCNT			(RALINK_FRAME_ENGINE_BASE+GDMA1_MIB_OFFSET+0x28)
#define GDMA1_RX_FERCNT			(RALINK_FRAME_ENGINE_BASE+GDMA1_MIB_OFFSET+0x2C)
#define GDMA1_RX_SERCNT			(RALINK_FRAME_ENGINE_BASE+GDMA1_MIB_OFFSET+0x30)
#define GDMA1_RX_LERCNT			(RALINK_FRAME_ENGINE_BASE+GDMA1_MIB_OFFSET+0x34)
#define GDMA1_RX_CERCNT			(RALINK_FRAME_ENGINE_BASE+GDMA1_MIB_OFFSET+0x38)
#define GDMA1_RX_FCCNT			(RALINK_FRAME_ENGINE_BASE+GDMA1_MIB_OFFSET+0x3C)

#if defined (CONFIG_RALINK_RT3883)
#define GDMA2_TX_GBCNT			(RALINK_FRAME_ENGINE_BASE+GDMA2_MIB_OFFSET+0x00)
#define GDMA2_TX_GPCNT			(RALINK_FRAME_ENGINE_BASE+GDMA2_MIB_OFFSET+0x04)
#define GDMA2_TX_SKIPCNT		(RALINK_FRAME_ENGINE_BASE+GDMA2_MIB_OFFSET+0x08)
#define GDMA2_TX_COLCNT			(RALINK_FRAME_ENGINE_BASE+GDMA2_MIB_OFFSET+0x0C)
#define GDMA2_RX_GBCNT			(RALINK_FRAME_ENGINE_BASE+GDMA2_MIB_OFFSET+0x20)
#define GDMA2_RX_GPCNT			(RALINK_FRAME_ENGINE_BASE+GDMA2_MIB_OFFSET+0x24)
#define GDMA2_RX_OERCNT			(RALINK_FRAME_ENGINE_BASE+GDMA2_MIB_OFFSET+0x28)
#define GDMA2_RX_FERCNT			(RALINK_FRAME_ENGINE_BASE+GDMA2_MIB_OFFSET+0x2C)
#define GDMA2_RX_SERCNT			(RALINK_FRAME_ENGINE_BASE+GDMA2_MIB_OFFSET+0x30)
#define GDMA2_RX_LERCNT			(RALINK_FRAME_ENGINE_BASE+GDMA2_MIB_OFFSET+0x34)
#define GDMA2_RX_CERCNT			(RALINK_FRAME_ENGINE_BASE+GDMA2_MIB_OFFSET+0x38)
#define GDMA2_RX_FCCNT			(RALINK_FRAME_ENGINE_BASE+GDMA2_MIB_OFFSET+0x3C)
#endif

#endif

/* ====================================== */
// GDMA bits
/* ====================================== */
#define GDM1_TCI_81XX			BIT(24)
#define GDM1_ICS_EN			BIT(22)
#define GDM1_TCS_EN			BIT(21)
#define GDM1_UCS_EN			BIT(20)
#if defined (CONFIG_RALINK_MT7621)
#define GDM1_INSV_EN			BIT(25)
/* JF registers are removed */
#define GDM1_JMB_EN			0
#else
#define GDM1_JMB_EN			BIT(19)
#endif
#define GDM1_DISPAD			BIT(18)
#define GDM1_DISCRC			BIT(17)
#define GDM1_STRPCRC			BIT(16)

//GDMA1 uni-cast frames destination port
#define GDM1_UFRC_P_PDMA		(0 << 12)
#if defined (CONFIG_RALINK_MT7621)
#define GDM1_UFRC_P_PPE			(4 << 12)
#define GDM1_UFRC_P_QDMA		(5 << 12)
#else
#define GDM1_UFRC_P_PPE			(6 << 12)
#endif

//GDMA1 broad-cast MAC address frames
#define GDM1_BFRC_P_PDMA		(0 << 8)
#if defined (CONFIG_RALINK_MT7621)
#define GDM1_BFRC_P_PPE			(4 << 8)
#define GDM1_BFRC_P_QDMA		(5 << 8)
#else
#define GDM1_BFRC_P_PPE			(6 << 8)
#endif

//GDMA1 multi-cast MAC address frames
#define GDM1_MFRC_P_PDMA		(0 << 4)
#if defined (CONFIG_RALINK_MT7621)
#define GDM1_MFRC_P_PPE			(4 << 4)
#define GDM1_MFRC_P_QDMA		(5 << 4)
#else
#define GDM1_MFRC_P_PPE			(6 << 4)
#endif

//GDMA1 other MAC address frames destination port
#define GDM1_OFRC_P_PDMA		(0 << 0)
#if defined (CONFIG_RALINK_MT7621)
#define GDM1_OFRC_P_PPE			(4 << 0)
#define GDM1_OFRC_P_QDMA		(5 << 0)
#else
#define GDM1_OFRC_P_PPE			(6 << 0)
#endif

#if defined (CONFIG_RALINK_MT7620) || defined (CONFIG_RALINK_MT7621)
/* checksum generator registers are removed */
#define ICS_GEN_EN			0
#define UCS_GEN_EN			0
#define TCS_GEN_EN			0
#else
#define ICS_GEN_EN			BIT(2)
#define UCS_GEN_EN			BIT(1)
#define TCS_GEN_EN			BIT(0)
#endif

/* ====================================== */
// PDMA bits
/* ====================================== */
#define PST_DRX_IDX1			BIT(17)
#define PST_DRX_IDX0			BIT(16)
#define PST_DTX_IDX3			BIT(3)
#define PST_DTX_IDX2			BIT(2)
#define PST_DTX_IDX1			BIT(1)
#define PST_DTX_IDX0			BIT(0)

#define RX_2B_OFFSET			BIT(31)
#define CSR_CLKGATE			BIT(30)
#define DESC_32B_EN			BIT(8)
#define TX_WB_DDONE			BIT(6)
#define RX_DMA_BUSY			BIT(3)
#define TX_DMA_BUSY			BIT(1)
#define RX_DMA_EN			BIT(2)
#define TX_DMA_EN			BIT(0)

#define PDMA_BT_SIZE_4DWORDS		(0<<4)
#define PDMA_BT_SIZE_8DWORDS		(1<<4)
#define PDMA_BT_SIZE_16DWORDS		(2<<4)
#define PDMA_BT_SIZE_32DWORDS		(3<<4)

#define INIT_VALUE_OF_RT3883_PSE_FQ_CFG	0xff908000
#define INIT_VALUE_OF_PSE_FQFC_CFG	0x80504000
#define INIT_VALUE_OF_FORCE_100_FD	0x1001BC01
#if defined (CONFIG_RTL8367) || defined (CONFIG_RTL8367_MODULE)
#define INIT_VALUE_OF_FORCE_1000_FD	0x0001DC01
#else
#define INIT_VALUE_OF_FORCE_1000_FD	0x1F01DC01
#endif

/*=========================================
      PDMA RX Descriptor Format define
=========================================*/

struct PDMA_rxdesc {
	unsigned int rxd_info1;
	unsigned int rxd_info2;
	unsigned int rxd_info3;
	unsigned int rxd_info4;
};

#define RX2_DMA_SDL0_GET(_x)		(((_x) >> 16) & 0x3fff)
#define RX2_DMA_SDL0_SET(_x)		(((_x) & 0x3fff) << 16)
#define RX2_DMA_LS1			BIT(14)
#define RX2_DMA_TAG			BIT(15)
#define RX2_DMA_LS0			BIT(30)
#define RX2_DMA_DONE			BIT(31)

#define RX3_DMA_VID(_x)			((_x) & 0xffff)
#define RX3_DMA_TPID(_x)		(((_x) >> 16) & 0xffff)

#if defined (CONFIG_RALINK_MT7621)
#define RX4_DMA_SP(_x)			(((_x) >> 19) & 0xf)
#define RX4_DMA_ALG_SET			(0xFF800000)
#define RX4_DMA_L4F			BIT(23)
#define RX4_DMA_L4FVLD			BIT(24)
#define RX4_DMA_TACK			BIT(25)
#define RX4_DMA_IP4F			BIT(26)
#define RX4_DMA_IP4			BIT(27)
#define RX4_DMA_IP6			BIT(28)
#elif defined (CONFIG_RALINK_MT7620)
#define RX4_DMA_SP(_x)			(((_x) >> 19) & 0x7)
#define RX4_DMA_ALG_SET			(0xFFC00000)
#define RX4_DMA_L4F			BIT(22)
#define RX4_DMA_L4FVLD			BIT(23)
#define RX4_DMA_TACK			BIT(24)
#define RX4_DMA_IP4F			BIT(25)
#define RX4_DMA_IP4			BIT(26)
#define RX4_DMA_IP6			BIT(27)
#else
#define RX4_DMA_ALG_SET			BIT(15)
#define RX4_DMA_SP(_x)			(((_x) >> 24) & 0x7)
#define RX4_DMA_L4F			BIT(28)
#define RX4_DMA_IPF			BIT(29)
#define RX4_DMA_L4FVLD			BIT(30)
#define RX4_DMA_IPFVLD			BIT(31)
#endif

/*=========================================
      PDMA TX Descriptor Format define
=========================================*/

struct PDMA_txdesc {
	unsigned int txd_info1;
	unsigned int txd_info2;
	unsigned int txd_info3;
	unsigned int txd_info4;
};

#define TXD_MAX_SEG_SIZE		0x3fff

#define TX2_DMA_SDL1(_x)		((_x) & 0x3fff)
#define TX2_DMA_LS1			BIT(14)
#define TX2_DMA_BURST			BIT(15)
#define TX2_DMA_SDL0(_x)		(((_x) & 0x3fff) << 16)
#define TX2_DMA_LS0			BIT(30)
#define TX2_DMA_DONE			BIT(31)

#if defined (CONFIG_RALINK_MT7621)
#define TX4_DMA_VLAN_TAG(_x)		((_x) & 0x1FFFF)
#define TX4_DMA_UDF(_x)			((_x) << 19)
#define TX4_DMA_FPORT(_x)		((_x) << 25)
#define TX4_DMA_TSO			BIT(28)
#elif defined (CONFIG_RALINK_MT7620)
#define TX4_DMA_VIDX(_x)		((_x) & 0xf)
#define TX4_DMA_VPRI(_x)		(((_x) & VLAN_PRIO_MASK) >> 9)
#define TX4_DMA_INSV			BIT(7)
#define TX4_DMA_UDF(_x)			((_x) << 15)
#define TX4_DMA_FP_BMAP(_x)		((_x) << 20)
#define TX4_DMA_TSO			BIT(28)
#else
#define TX4_DMA_VIDX(_x)		((_x) & 0xf)
#define TX4_DMA_VPRI(_x)		(((_x) & VLAN_PRIO_MASK) >> 9)
#define TX4_DMA_INSV			BIT(7)
#define TX4_DMA_QN(_x)			((_x) << 16)
#define TX4_DMA_PN(_x)			((_x) << 24)
#endif
#define TX4_DMA_TUI_CO(_x)		((_x) << 29)


#if defined (CONFIG_RALINK_MT7621)

/*=========================================
      QDMA TX Descriptor Format define
=========================================*/

struct QDMA_txdesc {
	unsigned int txd_info1;
	unsigned int txd_info2;
	unsigned int txd_info3;
	unsigned int txd_info4;
};

#define TX3_QDMA_QID(_x)	((_x) & 0x0F)
#define TX3_QDMA_SWC		BIT(14)
#define TX3_QDMA_BURST		BIT(15)
#define TX3_QDMA_SDL(_x)	(((_x) & 0x3fff) << 16)
#define TX3_QDMA_LS		BIT(30)
#define TX3_QDMA_OWN		BIT(31)

#define QDMA_RELATED		0x1800
#define  QTX_CFG_0		(RALINK_FRAME_ENGINE_BASE + QDMA_RELATED + 0x000)
#define  QTX_SCH_0		(RALINK_FRAME_ENGINE_BASE + QDMA_RELATED + 0x004)
#define  QTX_HEAD_0		(RALINK_FRAME_ENGINE_BASE + QDMA_RELATED + 0x008)
#define  QTX_TAIL_0		(RALINK_FRAME_ENGINE_BASE + QDMA_RELATED + 0x00C)

#define  QRX_BASE_PTR0		(RALINK_FRAME_ENGINE_BASE + QDMA_RELATED + 0x100)
#define  QRX_MAX_CNT0		(RALINK_FRAME_ENGINE_BASE + QDMA_RELATED + 0x104)
#define  QRX_CRX_IDX0		(RALINK_FRAME_ENGINE_BASE + QDMA_RELATED + 0x108)
#define  QRX_DRX_IDX0		(RALINK_FRAME_ENGINE_BASE + QDMA_RELATED + 0x10C)

#define  QRX_BASE_PTR1		(RALINK_FRAME_ENGINE_BASE + QDMA_RELATED + 0x110)
#define  QRX_MAX_CNT1		(RALINK_FRAME_ENGINE_BASE + QDMA_RELATED + 0x114)
#define  QRX_CRX_IDX1		(RALINK_FRAME_ENGINE_BASE + QDMA_RELATED + 0x118)
#define  QRX_DRX_IDX1		(RALINK_FRAME_ENGINE_BASE + QDMA_RELATED + 0x11C)

#define  QDMA_INFO		(RALINK_FRAME_ENGINE_BASE + QDMA_RELATED + 0x200)
#define  QDMA_GLO_CFG		(RALINK_FRAME_ENGINE_BASE + QDMA_RELATED + 0x204)
#define  QDMA_RST_IDX		(RALINK_FRAME_ENGINE_BASE + QDMA_RELATED + 0x208)
#define  QDMA_RST_CFG		(QDMA_RST_IDX)
#define  QDMA_DELAY_INT		(RALINK_FRAME_ENGINE_BASE + QDMA_RELATED + 0x20C)
#define  QDMA_FC_THRES		(RALINK_FRAME_ENGINE_BASE + QDMA_RELATED + 0x210)
#define  QDMA_TX_SCH		(RALINK_FRAME_ENGINE_BASE + QDMA_RELATED + 0x214)
#define  QDMA_INT_STS		(RALINK_FRAME_ENGINE_BASE + QDMA_RELATED + 0x218)
#define  QFE_INT_STATUS		(QDMA_INT_STS)
#define  QDMA_INT_MASK		(RALINK_FRAME_ENGINE_BASE + QDMA_RELATED + 0x21C)
#define  QFE_INT_ENABLE		(QDMA_INT_MASK)
#define  QDMA_TRTCM		(RALINK_FRAME_ENGINE_BASE + QDMA_RELATED + 0x220)
#define  QDMA_DATA0		(RALINK_FRAME_ENGINE_BASE + QDMA_RELATED + 0x224)
#define  QDMA_DATA1		(RALINK_FRAME_ENGINE_BASE + QDMA_RELATED + 0x228)
#define  QDMA_RED_THRES		(RALINK_FRAME_ENGINE_BASE + QDMA_RELATED + 0x22C)
#define  QDMA_TEST		(RALINK_FRAME_ENGINE_BASE + QDMA_RELATED + 0x230)
#define  QDMA_DMA		(RALINK_FRAME_ENGINE_BASE + QDMA_RELATED + 0x234)
#define  QDMA_BMU		(RALINK_FRAME_ENGINE_BASE + QDMA_RELATED + 0x238)

#define  QDMA_HRED1		(RALINK_FRAME_ENGINE_BASE + QDMA_RELATED + 0x240)
#define  QDMA_HRED2		(RALINK_FRAME_ENGINE_BASE + QDMA_RELATED + 0x244)
#define  QDMA_SRED1		(RALINK_FRAME_ENGINE_BASE + QDMA_RELATED + 0x248)
#define  QDMA_SRED2		(RALINK_FRAME_ENGINE_BASE + QDMA_RELATED + 0x24C)

#define  QTX_CTX_PTR		(RALINK_FRAME_ENGINE_BASE + QDMA_RELATED + 0x300)
#define  QTX_DTX_PTR		(RALINK_FRAME_ENGINE_BASE + QDMA_RELATED + 0x304)
#define  QTX_FWD_CNT		(RALINK_FRAME_ENGINE_BASE + QDMA_RELATED + 0x308)
#define  QTX_CRX_PTR		(RALINK_FRAME_ENGINE_BASE + QDMA_RELATED + 0x310)
#define  QTX_DRX_PTR		(RALINK_FRAME_ENGINE_BASE + QDMA_RELATED + 0x314)
#define  QTX_RLS_CNT		(RALINK_FRAME_ENGINE_BASE + QDMA_RELATED + 0x318)

#define  QDMA_FQ_HEAD		(RALINK_FRAME_ENGINE_BASE + QDMA_RELATED + 0x320)
#define  QDMA_FQ_TAIL		(RALINK_FRAME_ENGINE_BASE + QDMA_RELATED + 0x324)
#define  QDMA_FQ_CNT		(RALINK_FRAME_ENGINE_BASE + QDMA_RELATED + 0x328)
#define  QDMA_FQ_BLEN		(RALINK_FRAME_ENGINE_BASE + QDMA_RELATED + 0x32C)

#define  QTX_Q0MIN_BK		(RALINK_FRAME_ENGINE_BASE + QDMA_RELATED + 0x350)
#define  QTX_Q1MIN_BK		(RALINK_FRAME_ENGINE_BASE + QDMA_RELATED + 0x354)
#define  QTX_Q2MIN_BK		(RALINK_FRAME_ENGINE_BASE + QDMA_RELATED + 0x358)
#define  QTX_Q3MIN_BK		(RALINK_FRAME_ENGINE_BASE + QDMA_RELATED + 0x35C)
#define  QTX_Q0MAX_BK		(RALINK_FRAME_ENGINE_BASE + QDMA_RELATED + 0x360)
#define  QTX_Q1MAX_BK		(RALINK_FRAME_ENGINE_BASE + QDMA_RELATED + 0x364)
#define  QTX_Q2MAX_BK		(RALINK_FRAME_ENGINE_BASE + QDMA_RELATED + 0x368)
#define  QTX_Q3MAX_BK		(RALINK_FRAME_ENGINE_BASE + QDMA_RELATED + 0x36C)

#endif

#if defined (CONFIG_RAETH_QDMATX_QDMARX)
#define DMA_RX_CALC_IDX0	QRX_CRX_IDX0
#define DMA_RX_CALC_IDX1	QRX_CRX_IDX1
#else
#define DMA_RX_CALC_IDX0	RX_CALC_IDX0
#define DMA_RX_CALC_IDX1	RX_CALC_IDX1
#endif

#endif /* __RA_ETHREG_H__ */
