# Makefile for uClibc
#
# Copyright (C) 2000-2005 Erik Andersen <andersen@uclibc.org>
#
# Licensed under the LGPL v2.1, see the file COPYING.LIB in this tarball.
#

CSRC := brk.c __syscall_error.c sigaction.c mmap.c

SSRC := \
	__longjmp.S setjmp.S syscall.S bsd-setjmp.S bsd-_setjmp.S

ifneq ($(UCLIBC_HAS_THREADS_NATIVE),y)
SSRC += vfork.S clone.S
endif

ifeq ($(UCLIBC_LINUX_SPECIFIC),y)
ARCH_OBJ_FILTEROUT = sched_getcpu.c
ifeq ($(UCLIBC_HAS_TLS),y)
SSRC += sched_getcpu.S
endif
endif
