/* NETGEAR R6220 */

#define BOARD_PID		"R6220"
#define BOARD_NAME		"R6220"
#define BOARD_DESC		"NETGEAR R6220 Wireless Router"
#define BOARD_VENDOR_NAME	"NETGEAR Co., Ltd."
#define BOARD_VENDOR_URL	"https://www.netgear.com/"
#define BOARD_MODEL_URL		"http://www.netgear.com/"
#define BOARD_BOOT_TIME		25
#define BOARD_FLASH_TIME	120
#define BOARD_GPIO_BTN_RESET	14
#define BOARD_GPIO_BTN_WPS	7
#undef  BOARD_GPIO_LED_ALL
#define  BOARD_GPIO_LED_WIFI	16
#define BOARD_GPIO_LED_POWER	18
#undef  BOARD_GPIO_LED_LAN
#define BOARD_GPIO_LED_WAN	13
#define BOARD_GPIO_LED_USB	15
#undef  BOARD_GPIO_LED_ROUTER
#undef  BOARD_GPIO_PWR_USB
#undef  BOARD_GPIO_PWR_USB_ON
#define BOARD_HAS_5G_11AC	1
#define BOARD_NUM_ANT_5G_TX	2
#define BOARD_NUM_ANT_5G_RX	2
#define BOARD_NUM_ANT_2G_TX	2
#define BOARD_NUM_ANT_2G_RX	2
#define BOARD_NUM_ETH_LEDS	5
#define BOARD_NUM_ETH_EPHY	5
#define BOARD_HAS_EPHY_L1000	1
#define BOARD_HAS_EPHY_W1000	1
